// Italian vocabulary — add new entries here as you get worksheets from your tutor.
// Each entry: { it, en, type, cat, note, ex }
// Types: t-are, t-ere, t-ire, t-ireisc, t-irr, t-phrase, t-adj, t-prep, t-structure, t-think
// Cats: Verbs, Phrases, Structure, Adjectives, Colors, Prepositions, Tricky Pairs, Word Patterns, FARE Expressions

const VOCAB = [

  // ── VERBS -ARE ──────────────────────────────────────────────
  {it:"abitare",en:"to live (somewhere)",type:"t-are",cat:"Verbs",note:"abito, abiti, abita, abitiamo, abitate, abitano",ex:"Abito a Chicago.",conj:{type:"-ARE",io:"abito",tu:"abiti",lui:"abita",noi:"abitiamo",voi:"abitate",loro:"abitano"}},
  {it:"amare",en:"to love",type:"t-are",cat:"Verbs",note:"amo, ami, ama, amiamo, amate, amano",ex:"Amo l'italiano!",conj:{type:"-ARE",io:"amo",tu:"ami",lui:"ama",noi:"amiamo",voi:"amate",loro:"amano"}},
  {it:"ascoltare",en:"to listen to",type:"t-are",cat:"Verbs",note:"ascolto, ascolti, ascolta, ascoltiamo, ascoltate, ascoltano",ex:"Ascolto la musica.",conj:{type:"-ARE",io:"ascolto",tu:"ascolti",lui:"ascolta",noi:"ascoltiamo",voi:"ascoltate",loro:"ascoltano"}},
  {it:"aspettare",en:"to wait for",type:"t-are",cat:"Verbs",note:"aspetto, aspetti, aspetta...",ex:"Aspetta un momento!",conj:{type:"-ARE",io:"aspetto",tu:"aspetti",lui:"aspetta",noi:"aspettiamo",voi:"aspettate",loro:"aspettano"}},
  {it:"ballare",en:"to dance",type:"t-are",cat:"Verbs",note:"ballo, balli, balla, balliamo, ballate, ballano",ex:"Vuoi ballare?",conj:{type:"-ARE",io:"ballo",tu:"balli",lui:"balla",noi:"balliamo",voi:"ballate",loro:"ballano"}},
  {it:"camminare",en:"to walk",type:"t-are",cat:"Verbs",note:"cammino, cammini, cammina...",ex:"Ho camminato tutto il giorno.",conj:{type:"-ARE",io:"cammino",tu:"cammini",lui:"cammina",noi:"camminiamo",voi:"camminate",loro:"camminano"}},
  {it:"cantare",en:"to sing",type:"t-are",cat:"Verbs",note:"canto, canti, canta, cantiamo, cantate, cantano",ex:"Lui canta bene.",conj:{type:"-ARE",io:"canto",tu:"canti",lui:"canta",noi:"cantiamo",voi:"cantate",loro:"cantano"}},
  {it:"cenare",en:"to have dinner",type:"t-are",cat:"Verbs",note:"ceno, ceni, cena, ceniamo, cenate, cenano",ex:"A che ora ceni?",conj:{type:"-ARE",io:"ceno",tu:"ceni",lui:"cena",noi:"ceniamo",voi:"cenate",loro:"cenano"}},
  {it:"cercare",en:"to look for / try",type:"t-are",cat:"Verbs",note:"cerco, cerchi, cerca...",ex:"Sto cercando il ristorante.",conj:{type:"-ARE",io:"cerco",tu:"cerchi",lui:"cerca",noi:"cerchiamo",voi:"cercate",loro:"cercano"}},
  {it:"chiamare",en:"to call",type:"t-are",cat:"Verbs",note:"chiamo, chiami, chiama...",ex:"Ti chiamo dopo.",conj:{type:"-ARE",io:"chiamo",tu:"chiami",lui:"chiama",noi:"chiamiamo",voi:"chiamate",loro:"chiamano"}},
  {it:"comprare",en:"to buy",type:"t-are",cat:"Verbs",note:"compro, compri, compra...",ex:"Voglio comprare un caffè.",conj:{type:"-ARE",io:"compro",tu:"compri",lui:"compra",noi:"compriamo",voi:"comprate",loro:"comprano"}},
  {it:"cucinare",en:"to cook",type:"t-are",cat:"Verbs",note:"cucino, cucini, cucina...",ex:"Cucino la pasta stasera.",conj:{type:"-ARE",io:"cucino",tu:"cucini",lui:"cucina",noi:"cuciniamo",voi:"cucinate",loro:"cucinano"}},
  {it:"domandare",en:"to ask (a question)",type:"t-are",cat:"Verbs",note:"domando, domandi, domanda...",ex:"Mi ha domandato una cosa.",conj:{type:"-ARE",io:"domando",tu:"domandi",lui:"domanda",noi:"domandiamo",voi:"domandate",loro:"domandano"}},
  {it:"guardare",en:"to watch / look at",type:"t-are",cat:"Verbs",note:"guardo, guardi, guarda...",ex:"Guardo la TV la sera.",conj:{type:"-ARE",io:"guardo",tu:"guardi",lui:"guarda",noi:"guardiamo",voi:"guardate",loro:"guardano"}},
  {it:"imparare",en:"to learn",type:"t-are",cat:"Verbs",note:"imparo, impari, impara...",ex:"Sto imparando l'italiano.",conj:{type:"-ARE",io:"imparo",tu:"impari",lui:"impara",noi:"impariamo",voi:"imparate",loro:"imparano"}},
  {it:"incontrare",en:"to meet / run into",type:"t-are",cat:"Verbs",note:"incontro, incontri, incontra...",ex:"Ho incontrato Marco al bar.",conj:{type:"-ARE",io:"incontro",tu:"incontri",lui:"incontra",noi:"incontriamo",voi:"incontrate",loro:"incontrano"}},
  {it:"lavorare",en:"to work",type:"t-are",cat:"Verbs",note:"lavoro, lavori, lavora...",ex:"Lavoro in centro.",conj:{type:"-ARE",io:"lavoro",tu:"lavori",lui:"lavora",noi:"lavoriamo",voi:"lavorate",loro:"lavorano"}},
  {it:"mangiare",en:"to eat",type:"t-are",cat:"Verbs",note:"mangio, mangi, mangia...",ex:"Cosa mangi a pranzo?",conj:{type:"-ARE",io:"mangio",tu:"mangi",lui:"mangia",noi:"mangiamo",voi:"mangiate",loro:"mangiano"}},
  {it:"pagare",en:"to pay",type:"t-are",cat:"Verbs",note:"pago, paghi, paga...",ex:"Posso pagare con la carta?",conj:{type:"-ARE",io:"pago",tu:"paghi",lui:"paga",noi:"paghiamo",voi:"pagate",loro:"pagano"}},
  {it:"parlare",en:"to speak",type:"t-are",cat:"Verbs",note:"parlo, parli, parla...",ex:"Parli italiano?",conj:{type:"-ARE",io:"parlo",tu:"parli",lui:"parla",noi:"parliamo",voi:"parlate",loro:"parlano"}},
  {it:"pensare",en:"to think / consider",type:"t-are",cat:"Verbs",note:"penso, pensi, pensa...",ex:"Cosa pensi?",conj:{type:"-ARE",io:"penso",tu:"pensi",lui:"pensa",noi:"pensiamo",voi:"pensate",loro:"pensano"}},
  {it:"portare",en:"to carry / bring",type:"t-are",cat:"Verbs",note:"porto, porti, porta...",ex:"Mi porta il conto?",conj:{type:"-ARE",io:"porto",tu:"porti",lui:"porta",noi:"portiamo",voi:"portate",loro:"portano"}},
  {it:"sperare",en:"to hope",type:"t-are",cat:"Verbs",note:"spero, speri, spera...",ex:"Speriamo!",conj:{type:"-ARE",io:"spero",tu:"speri",lui:"spera",noi:"speriamo",voi:"sperate",loro:"sperano"}},
  {it:"studiare",en:"to study",type:"t-are",cat:"Verbs",note:"studio, studi, studia...",ex:"Studio l'italiano ogni giorno.",conj:{type:"-ARE",io:"studio",tu:"studi",lui:"studia",noi:"studiamo",voi:"studiate",loro:"studiano"}},
  {it:"tornare",en:"to return / come back",type:"t-are",cat:"Verbs",note:"torno, torni, torna...",ex:"Torno a casa alle 7.",conj:{type:"-ARE",io:"torno",tu:"torni",lui:"torna",noi:"torniamo",voi:"tornate",loro:"tornano"}},
  {it:"trovare",en:"to find",type:"t-are",cat:"Verbs",note:"trovo, trovi, trova...",ex:"Non riesco a trovare il ristorante.",conj:{type:"-ARE",io:"trovo",tu:"trovi",lui:"trova",noi:"troviamo",voi:"trovate",loro:"trovano"}},
  {it:"dimenticare",en:"to forget",type:"t-are",cat:"Verbs",note:"dimentico, dimentichi, dimentica...",ex:"Ho dimenticato!"},
  {it:"ricordare",en:"to remember",type:"t-are",cat:"Verbs",note:"ricordo / mi ricordo...",ex:"Non ricordo il suo nome."},
  {it:"sembrare",en:"to seem / look like",type:"t-are",cat:"Verbs",note:"sembro, sembri, sembra...",ex:"Sembra buono!"},

  // ── VERBS -ERE ──────────────────────────────────────────────
  {it:"chiedere",en:"to ask for / request",type:"t-ere",cat:"Verbs",note:"chiedo, chiedi, chiede...",ex:"Posso chiederti una cosa?",conj:{type:"-ERE",io:"chiedo",tu:"chiedi",lui:"chiede",noi:"chiediamo",voi:"chiedete",loro:"chiedono"}},
  {it:"conoscere",en:"to know (person/place)",type:"t-ere",cat:"Verbs",note:"conosco, conosci, conosce...",ex:"Conosci Marco?",conj:{type:"-ERE",io:"conosco",tu:"conosci",lui:"conosce",noi:"conosciamo",voi:"conoscete",loro:"conoscono"}},
  {it:"credere",en:"to think / believe",type:"t-ere",cat:"Verbs",note:"credo, credi, crede...",ex:"Credo di sì.",conj:{type:"-ERE",io:"credo",tu:"credi",lui:"crede",noi:"crediamo",voi:"credete",loro:"credono"}},
  {it:"leggere",en:"to read",type:"t-ere",cat:"Verbs",note:"leggo, leggi, legge...",ex:"Leggo ogni sera.",conj:{type:"-ERE",io:"leggo",tu:"leggi",lui:"legge",noi:"leggiamo",voi:"leggete",loro:"leggono"}},
  {it:"prendere",en:"to take / order",type:"t-ere",cat:"Verbs",note:"prendo, prendi, prende...",ex:"Prendo un caffè.",conj:{type:"-ERE",io:"prendo",tu:"prendi",lui:"prende",noi:"prendiamo",voi:"prendete",loro:"prendono"}},
  {it:"scrivere",en:"to write",type:"t-ere",cat:"Verbs",note:"scrivo, scrivi, scrive...",ex:"Scrivo un messaggio.",conj:{type:"-ERE",io:"scrivo",tu:"scrivi",lui:"scrive",noi:"scriviamo",voi:"scrivete",loro:"scrivono"}},
  {it:"vedere",en:"to see",type:"t-ere",cat:"Verbs",note:"vedo, vedi, vede...",ex:"Ci vediamo domani!",conj:{type:"-ERE",io:"vedo",tu:"vedi",lui:"vede",noi:"vediamo",voi:"vedete",loro:"vedono"}},
  {it:"vivere",en:"to live (be alive)",type:"t-ere",cat:"Verbs",note:"vivo, vivi, vive...",ex:"Vivo a Chicago.",conj:{type:"-ERE",io:"vivo",tu:"vivi",lui:"vive",noi:"viviamo",voi:"vivete",loro:"vivono"}},
  {it:"decidere",en:"to decide",type:"t-ere",cat:"Verbs",note:"decido, decidi, decide...",ex:"Ho deciso!"},

  // ── VERBS -IRE ──────────────────────────────────────────────
  {it:"aprire",en:"to open",type:"t-ire",cat:"Verbs",note:"apro, apri, apre...",ex:"A che ora si apre?",conj:{type:"-IRE",io:"apro",tu:"apri",lui:"apre",noi:"apriamo",voi:"aprite",loro:"aprono"}},
  {it:"dormire",en:"to sleep",type:"t-ire",cat:"Verbs",note:"dormo, dormi, dorme...",ex:"Dormo tardi il weekend.",conj:{type:"-IRE",io:"dormo",tu:"dormi",lui:"dorme",noi:"dormiamo",voi:"dormite",loro:"dormono"}},
  {it:"partire",en:"to leave / depart",type:"t-ire",cat:"Verbs",note:"parto, parti, parte...",ex:"Parto per Roma domani.",conj:{type:"-IRE",io:"parto",tu:"parti",lui:"parte",noi:"partiamo",voi:"partite",loro:"partono"}},
  {it:"scoprire",en:"to discover",type:"t-ire",cat:"Verbs",note:"scopro, scopri, scopre...",ex:"Scopro sempre cose nuove.",conj:{type:"-IRE",io:"scopro",tu:"scopri",lui:"scopre",noi:"scopriamo",voi:"scoprite",loro:"scoprono"}},
  {it:"sentire",en:"to hear / feel",type:"t-ire",cat:"Verbs",note:"sento, senti, sente...",ex:"Non ti sento bene.",conj:{type:"-IRE",io:"sento",tu:"senti",lui:"sente",noi:"sentiamo",voi:"sentite",loro:"sentono"}},

  // ── VERBS -IRE/ISC ────────────────────────────────────────────
  {it:"capire",en:"to understand",type:"t-ireisc",cat:"Verbs",note:"capisco, capisci, capisce, capiamo, capite, capiscono",ex:"Non capisco. Puoi ripetere?",conj:{type:"-IRE/isc",io:"capisco",tu:"capisci",lui:"capisce",noi:"capiamo",voi:"capite",loro:"capiscono"}},
  {it:"finire",en:"to finish",type:"t-ireisc",cat:"Verbs",note:"finisco, finisci, finisce, finiamo, finite, finiscono",ex:"A che ora finisce?",conj:{type:"-IRE/isc",io:"finisco",tu:"finisci",lui:"finisce",noi:"finiamo",voi:"finite",loro:"finiscono"}},
  {it:"preferire",en:"to prefer",type:"t-ireisc",cat:"Verbs",note:"preferisco, preferisci, preferisce...",ex:"Preferisco il vino rosso.",conj:{type:"-IRE/isc",io:"preferisco",tu:"preferisci",lui:"preferisce",noi:"preferiamo",voi:"preferite",loro:"preferiscono"}},
  {it:"pulire",en:"to clean",type:"t-ireisc",cat:"Verbs",note:"pulisco, pulisci, pulisce...",ex:"Pulisco la casa il sabato.",conj:{type:"-IRE/isc",io:"pulisco",tu:"pulisci",lui:"pulisce",noi:"puliamo",voi:"pulite",loro:"puliscono"}},

  // ── IRREGULAR VERBS ───────────────────────────────────────────
  {it:"andare",en:"to go",type:"t-irr",cat:"Verbs",note:"vado, vai, va, andiamo, andate, vanno",ex:"Vado al bar.",conj:{type:"IRR",io:"vado",tu:"vai",lui:"va",noi:"andiamo",voi:"andate",loro:"vanno"}},
  {it:"avere",en:"to have",type:"t-irr",cat:"Verbs",note:"ho, hai, ha, abbiamo, avete, hanno",ex:"Ho fame!",conj:{type:"IRR",io:"ho",tu:"hai",lui:"ha",noi:"abbiamo",voi:"avete",loro:"hanno"}},
  {it:"bere",en:"to drink",type:"t-irr",cat:"Verbs",note:"bevo, bevi, beve, beviamo, bevete, bevono",ex:"Cosa bevi?",conj:{type:"IRR",io:"bevo",tu:"bevi",lui:"beve",noi:"beviamo",voi:"bevete",loro:"bevono"}},
  {it:"dare",en:"to give",type:"t-irr",cat:"Verbs",note:"do, dai, dà, diamo, date, danno",ex:"Mi dà il conto?",conj:{type:"IRR",io:"do",tu:"dai",lui:"da",noi:"diamo",voi:"date",loro:"danno"}},
  {it:"dire",en:"to say / tell",type:"t-irr",cat:"Verbs",note:"dico, dici, dice, diciamo, dite, dicono",ex:"Come si dice?",conj:{type:"IRR",io:"dico",tu:"dici",lui:"dice",noi:"diciamo",voi:"dite",loro:"dicono"}},
  {it:"essere",en:"to be",type:"t-irr",cat:"Verbs",note:"sono, sei, è, siamo, siete, sono",ex:"Sono americano.",conj:{type:"IRR",io:"sono",tu:"sei",lui:"e",noi:"siamo",voi:"siete",loro:"sono"}},
  {it:"fare",en:"to do / make",type:"t-irr",cat:"Verbs",note:"faccio, fai, fa, facciamo, fate, fanno",ex:"Cosa fai stasera?",conj:{type:"IRR",io:"faccio",tu:"fai",lui:"fa",noi:"facciamo",voi:"fate",loro:"fanno"}},
  {it:"piacere",en:"to please (mi piace = I like)",type:"t-irr",cat:"Verbs",note:"piaccio, piaci, piace, piacciamo, piacete, piacciono",ex:"Mi piace l'italiano!",conj:{type:"IRR",io:"piaccio",tu:"piaci",lui:"piace",noi:"piacciamo",voi:"piacete",loro:"piacciono"}},
  {it:"potere",en:"to be able / can",type:"t-irr",cat:"Verbs",note:"posso, puoi, può, possiamo, potete, possono",ex:"Posso avere il conto?",conj:{type:"IRR",io:"posso",tu:"puoi",lui:"puo",noi:"possiamo",voi:"potete",loro:"possono"}},
  {it:"rimanere",en:"to stay / remain",type:"t-irr",cat:"Verbs",note:"rimango, rimani, rimane...",ex:"Rimango a casa stasera.",conj:{type:"IRR",io:"rimango",tu:"rimani",lui:"rimane",noi:"rimaniamo",voi:"rimanete",loro:"rimangono"}},
  {it:"sapere",en:"to know (fact/skill)",type:"t-irr",cat:"Verbs",note:"so, sai, sa, sappiamo, sapete, sanno",ex:"Non lo so!",conj:{type:"IRR",io:"so",tu:"sai",lui:"sa",noi:"sappiamo",voi:"sapete",loro:"sanno"}},
  {it:"stare",en:"to be / stay (temp.)",type:"t-irr",cat:"Verbs",note:"sto, stai, sta, stiamo, state, stanno",ex:"Come stai?",conj:{type:"IRR",io:"sto",tu:"stai",lui:"sta",noi:"stiamo",voi:"state",loro:"stanno"}},
  {it:"uscire",en:"to go out",type:"t-irr",cat:"Verbs",note:"esco, esci, esce, usciamo, uscite, escono",ex:"Esci stasera?",conj:{type:"IRR",io:"esco",tu:"esci",lui:"esce",noi:"usciamo",voi:"uscite",loro:"escono"}},
  {it:"venire",en:"to come",type:"t-irr",cat:"Verbs",note:"vengo, vieni, viene, veniamo, venite, vengono",ex:"Vieni con me?",conj:{type:"IRR",io:"vengo",tu:"vieni",lui:"viene",noi:"veniamo",voi:"venite",loro:"vengono"}},
  {it:"volere",en:"to want",type:"t-irr",cat:"Verbs",note:"voglio, vuoi, vuole, vogliamo, volete, vogliono",ex:"Vorrei un caffè, per favore.",conj:{type:"IRR",io:"voglio",tu:"vuoi",lui:"vuole",noi:"vogliamo",voi:"volete",loro:"vogliono"}},
  {it:"dovere",en:"to have to / must",type:"t-irr",cat:"Verbs",note:"devo, devi, deve, dobbiamo, dovete, devono",ex:"Devo studiare."},
  {it:"sentirsi",en:"to feel (about yourself)",type:"t-irr",cat:"Verbs",note:"mi sento, ti senti, si sente...",ex:"Come ti senti?"},

  // ── KEY PHRASES ───────────────────────────────────────────────
  {it:"Credo di sì.",en:"I think so.",type:"t-phrase",cat:"Phrases",note:"Use when answering yes/no with uncertainty",ex:"Viene Marco? Credo di sì."},
  {it:"Credo di no.",en:"I don't think so.",type:"t-phrase",cat:"Phrases",note:"Uncertain negative answer",ex:"È chiuso? Credo di no."},
  {it:"Non ci credo!",en:"I don't believe it! No way!",type:"t-phrase",cat:"Phrases",note:"Expressing disbelief or surprise",ex:""},
  {it:"Non lo so.",en:"I don't know.",type:"t-phrase",cat:"Phrases",note:"Most used phrase — say it with confidence!",ex:"Dove sei? Non lo so!"},
  {it:"Speriamo!",en:"Let's hope! Hopefully!",type:"t-phrase",cat:"Phrases",note:"One of the most common Italian expressions",ex:"Fa bel tempo? Speriamo!"},
  {it:"Non capisco.",en:"I don't understand.",type:"t-phrase",cat:"Phrases",note:"Say this confidently — Italians will help you",ex:"Puoi ripetere?"},
  {it:"Ho capito!",en:"Got it! I understand!",type:"t-phrase",cat:"Phrases",note:"Confirming comprehension",ex:""},
  {it:"Ho dimenticato!",en:"I forgot!",type:"t-phrase",cat:"Phrases",note:"Very useful for a beginner",ex:"Il portafoglio! Ho dimenticato!"},
  {it:"Ho deciso!",en:"I've decided!",type:"t-phrase",cat:"Phrases",note:"Final answer!",ex:"Prendo gli spaghetti. Ho deciso!"},
  {it:"Sembra buono!",en:"It looks/seems good!",type:"t-phrase",cat:"Phrases",note:"Reacting to food, a plan, an idea",ex:""},
  {it:"Mi sento bene.",en:"I feel fine / well.",type:"t-phrase",cat:"Phrases",note:"Standard answer to 'Come stai?'",ex:""},
  {it:"Ci vediamo!",en:"See you! / Talk soon!",type:"t-phrase",cat:"Phrases",note:"Common goodbye",ex:""},
  {it:"Come stai?",en:"How are you?",type:"t-phrase",cat:"Phrases",note:"Informal — use with friends",ex:""},
  {it:"Sto bene, grazie.",en:"I'm fine, thank you.",type:"t-phrase",cat:"Phrases",note:"Answer to come stai?",ex:""},
  {it:"Prego!",en:"You're welcome! / Please!",type:"t-phrase",cat:"Phrases",note:"Response to grazie",ex:""},
  {it:"Scusa! / Scusi!",en:"Excuse me! / Sorry!",type:"t-phrase",cat:"Phrases",note:"Scusa = informal, Scusi = formal",ex:""},
  {it:"Vorrei...",en:"I would like...",type:"t-phrase",cat:"Phrases",note:"Most polite way to order — always use this!",ex:"Vorrei un caffè, per favore."},
  {it:"Posso avere...?",en:"Can I have...?",type:"t-phrase",cat:"Phrases",note:"Polite request",ex:"Posso avere il conto?"},
  {it:"Il conto, per favore!",en:"The check, please!",type:"t-phrase",cat:"Phrases",note:"Essential restaurant phrase",ex:""},
  {it:"Dov'è il bagno?",en:"Where is the bathroom?",type:"t-phrase",cat:"Phrases",note:"Most universal travel phrase",ex:""},
  {it:"Parla lentamente, per favore.",en:"Please speak slowly.",type:"t-phrase",cat:"Phrases",note:"Essential for learners!",ex:""},
  {it:"Non parlo bene l'italiano.",en:"I don't speak Italian well.",type:"t-phrase",cat:"Phrases",note:"Humble opener — Italians love it",ex:""},
  {it:"Sto imparando l'italiano.",en:"I'm learning Italian.",type:"t-phrase",cat:"Phrases",note:"Great conversation starter",ex:""},
  {it:"Correggimi, per favore!",en:"Correct me, please!",type:"t-phrase",cat:"Phrases",note:"Ask natives to help you improve",ex:""},
  {it:"Che coincidenza!",en:"What a coincidence!",type:"t-phrase",cat:"Phrases",note:"You'll hear this constantly",ex:""},
  {it:"In bocca al lupo!",en:"Good luck! (lit: into the wolf's mouth)",type:"t-phrase",cat:"Phrases",note:"Response: Crepi! (May it die!)",ex:""},
  {it:"Da portare via.",en:"To go / Takeaway.",type:"t-phrase",cat:"Phrases",note:"At a bar or restaurant",ex:""},
  {it:"Posso pagare con la carta?",en:"Can I pay by card?",type:"t-phrase",cat:"Phrases",note:"Very important in Italy!",ex:""},
  {it:"Si accettano carte?",en:"Do you accept cards?",type:"t-phrase",cat:"Phrases",note:"accettare = to accept",ex:""},
  {it:"Anch'io!",en:"Me too!",type:"t-phrase",cat:"Phrases",note:"anch' + io — apostrophe before vowel",ex:""},
  {it:"Neanche io.",en:"Me neither.",type:"t-phrase",cat:"Phrases",note:"negative version of anch'io",ex:""},
  {it:"Non c'è problema!",en:"No problem!",type:"t-phrase",cat:"Phrases",note:"One of the most useful phrases",ex:""},
  {it:"Che cosa?",en:"What? / What thing?",type:"t-phrase",cat:"Phrases",note:"cosa = thing — che cosa = what",ex:""},
  {it:"Qualcosa non va.",en:"Something is wrong.",type:"t-phrase",cat:"Phrases",note:"qualcosa = something",ex:""},
  {it:"Niente, grazie.",en:"Nothing, thanks.",type:"t-phrase",cat:"Phrases",note:"niente = nothing",ex:""},

  // ── STRUCTURE WORDS ───────────────────────────────────────────
  {it:"C'è...",en:"There is...",type:"t-structure",cat:"Structure",note:"c'è = ci + è — singular",ex:"C'è un bar qui vicino?"},
  {it:"Ci sono...",en:"There are...",type:"t-structure",cat:"Structure",note:"ci sono = plural",ex:"Ci sono tavoli liberi?"},
  {it:"Non c'è...",en:"There isn't...",type:"t-structure",cat:"Structure",note:"Non c'è problema = No problem!",ex:"Non c'è problema!"},
  {it:"Ecco!",en:"Here it is! / There you go!",type:"t-structure",cat:"Structure",note:"For presenting or pointing out something",ex:"Ecco il menù!"},
  {it:"Eccomi!",en:"Here I am!",type:"t-structure",cat:"Structure",note:"ecco + mi",ex:"Eccomi! Sono arrivato!"},
  {it:"Come si dice?",en:"How do you say...?",type:"t-structure",cat:"Structure",note:"si + verb = impersonal construction",ex:"Come si dice 'hello' in italiano?"},
  {it:"Si mangia bene qui.",en:"The food is good here.",type:"t-structure",cat:"Structure",note:"si = impersonal — one eats well here",ex:""},
  {it:"Mi piace...",en:"I like... (singular thing)",type:"t-structure",cat:"Structure",note:"The THING is the subject — it pleases me",ex:"Mi piace la pasta."},
  {it:"Mi piacciono...",en:"I like... (plural things)",type:"t-structure",cat:"Structure",note:"plural thing = mi piacciono",ex:"Mi piacciono i cani."},
  {it:"Ho bisogno di...",en:"I need...",type:"t-structure",cat:"Structure",note:"Always DI after bisogno!",ex:"Ho bisogno di aiuto."},
  {it:"Ho voglia di...",en:"I feel like...",type:"t-structure",cat:"Structure",note:"ho voglia di = I fancy something",ex:"Ho voglia di pizza!"},
  {it:"Sto + -ando/-endo",en:"I am doing... (right now)",type:"t-structure",cat:"Structure",note:"-ARE → -ando | -ERE/-IRE → -endo",ex:"Sto mangiando."},
  {it:"Vado a + infinitive",en:"I'm going to...",type:"t-structure",cat:"Structure",note:"Always A between vado and next verb",ex:"Vado a mangiare."},
  {it:"Andiamo a...!",en:"Let's go...!",type:"t-structure",cat:"Structure",note:"andiamo = let's go",ex:"Andiamo a mangiare!"},
  {it:"Ho fame.",en:"I'm hungry.",type:"t-structure",cat:"Structure",note:"avere + noun for physical states",ex:"Ho fame — andiamo a mangiare!"},
  {it:"Ho sete.",en:"I'm thirsty.",type:"t-structure",cat:"Structure",note:"ho sete = I have thirst",ex:""},
  {it:"Ho caldo.",en:"I'm hot.",type:"t-structure",cat:"Structure",note:"ho caldo = I have heat",ex:""},
  {it:"Ho freddo.",en:"I'm cold.",type:"t-structure",cat:"Structure",note:"ho freddo = I have cold",ex:""},
  {it:"Ho sonno.",en:"I'm sleepy.",type:"t-structure",cat:"Structure",note:"ho sonno = I have sleep",ex:""},
  {it:"Ho ragione.",en:"I'm right.",type:"t-structure",cat:"Structure",note:"ho ragione = I have reason",ex:""},
  {it:"Ho torto.",en:"I'm wrong.",type:"t-structure",cat:"Structure",note:"ho torto = I have wrong",ex:""},
  {it:"Già",en:"already",type:"t-structure",cat:"Structure",note:"Ho già mangiato. = I already ate.",ex:""},
  {it:"Non ancora",en:"not yet",type:"t-structure",cat:"Structure",note:"Non ho ancora mangiato. = I haven't eaten yet.",ex:""},
  {it:"Non più",en:"no longer / not anymore",type:"t-structure",cat:"Structure",note:"Non abito più a Roma.",ex:""},
  {it:"Ancora",en:"still / again / yet",type:"t-structure",cat:"Structure",note:"Abito ancora qui. = I still live here.",ex:""},
  {it:"Sempre",en:"always",type:"t-structure",cat:"Structure",note:"goes AFTER the verb",ex:"Vado sempre al bar."},
  {it:"Spesso",en:"often",type:"t-structure",cat:"Structure",note:"goes AFTER the verb",ex:"Mangio spesso la pizza."},
  {it:"Di solito",en:"usually",type:"t-structure",cat:"Structure",note:"goes at START of sentence",ex:"Di solito studio la sera."},
  {it:"Qualche volta",en:"sometimes",type:"t-structure",cat:"Structure",note:"goes at START of sentence",ex:"Qualche volta cucino a casa."},
  {it:"Non... mai",en:"never",type:"t-structure",cat:"Structure",note:"non BEFORE verb, mai AFTER",ex:"Non mangio mai carne."},
  {it:"Forse",en:"maybe / perhaps",type:"t-structure",cat:"Structure",note:"Forse sì, forse no.",ex:"Viene? Forse."},
  {it:"Quindi",en:"therefore / so",type:"t-structure",cat:"Structure",note:"logical consequence",ex:"Studio, quindi imparo."},
  {it:"Allora",en:"so / well then",type:"t-structure",cat:"Structure",note:"starting a sentence — very common!",ex:"Allora, andiamo?"},
  {it:"Finora",en:"so far / until now",type:"t-structure",cat:"Structure",note:"fino + ora",ex:"Finora amo questa città."},
  {it:"Davvero?",en:"Really? / Truly?",type:"t-structure",cat:"Structure",note:"davvero = really/truly",ex:""},
  {it:"Subito!",en:"Right away! / Immediately!",type:"t-structure",cat:"Structure",note:"Very common in service situations",ex:""},

  // ── ADJECTIVES ────────────────────────────────────────────────
  {it:"alto / alta",en:"tall",type:"t-adj",cat:"Adjectives",note:"-o/-a type: alti/alte (plural)",ex:"È molto alto."},
  {it:"basso / bassa",en:"short (height)",type:"t-adj",cat:"Adjectives",note:"-o/-a type: bassi/basse",ex:""},
  {it:"bello / bella",en:"beautiful / nice",type:"t-adj",cat:"Adjectives",note:"bel before m. nouns: bel ragazzo",ex:"Che bella città!"},
  {it:"brutto / brutta",en:"ugly / bad",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Fa brutto tempo oggi."},
  {it:"buono / buona",en:"good (quality)",type:"t-adj",cat:"Adjectives",note:"buon before masc. noun: buon giorno",ex:"È molto buono!"},
  {it:"cattivo / cattiva",en:"bad / mean",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:""},
  {it:"grande",en:"big / large",type:"t-adj",cat:"Adjectives",note:"-e type: 2 forms only (grande/grandi)",ex:"Una grande opportunità."},
  {it:"piccolo / piccola",en:"small / little",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Un piccolo problema."},
  {it:"caldo / calda",en:"hot / warm",type:"t-adj",cat:"Adjectives",note:"Ho caldo = I'm hot",ex:"È molto caldo oggi!"},
  {it:"freddo / fredda",en:"cold",type:"t-adj",cat:"Adjectives",note:"Ho freddo = I'm cold",ex:"Fa freddo!"},
  {it:"simpatico / simpatica",en:"friendly / likeable",type:"t-adj",cat:"Adjectives",note:"simpatici/simpatiche (hard c)",ex:"È molto simpatico."},
  {it:"stanco / stanca",en:"tired",type:"t-adj",cat:"Adjectives",note:"stanchi/stanche (hard c)",ex:"Sono stanco — ho camminato tutto il giorno."},
  {it:"contento / contenta",en:"happy / pleased",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Sono molto contento!"},
  {it:"facile",en:"easy",type:"t-adj",cat:"Adjectives",note:"-e type: facile/facili",ex:"È più facile di così."},
  {it:"difficile",en:"difficult",type:"t-adj",cat:"Adjectives",note:"-e type",ex:"È molto difficile."},
  {it:"veloce",en:"fast",type:"t-adj",cat:"Adjectives",note:"-e type | velocità = speed",ex:"Mangia troppo veloce!"},
  {it:"lento / lenta",en:"slow",type:"t-adj",cat:"Adjectives",note:"lentamente = slowly",ex:"Parla lentamente, per favore."},
  {it:"nuovo / nuova",en:"new",type:"t-adj",cat:"Adjectives",note:"-o/-a type | novità = news",ex:"Ho una nuova amica."},
  {it:"vecchio / vecchia",en:"old",type:"t-adj",cat:"Adjectives",note:"vecchi/vecchie (hard c)",ex:"Una vecchia tradizione."},
  {it:"aperto / aperta",en:"open",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Il bar è aperto."},
  {it:"chiuso / chiusa",en:"closed",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"È chiuso il lunedì."},
  {it:"interessante",en:"interesting",type:"t-adj",cat:"Adjectives",note:"-e type",ex:"È molto interessante!"},
  {it:"noioso / noiosa",en:"boring",type:"t-adj",cat:"Adjectives",note:"-o/-a type | noia = boredom",ex:""},
  {it:"pieno / piena",en:"full",type:"t-adj",cat:"Adjectives",note:"-o/-a type | riempire = to fill",ex:"Sono pieno! Ho mangiato troppo."},
  {it:"vuoto / vuota",en:"empty",type:"t-adj",cat:"Adjectives",note:"-o/-a type | void",ex:"Il bicchiere è vuoto."},

  // ── COLORS ────────────────────────────────────────────────────
  {it:"rosso / rossa",en:"red",type:"t-adj",cat:"Colors",note:"4 forms: rosso/rossa/rossi/rosse",ex:"Vino rosso, per favore."},
  {it:"blu",en:"dark blue",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:"Una giacca blu."},
  {it:"verde",en:"green",type:"t-adj",cat:"Colors",note:"-e type: verde/verdi",ex:"La bandiera italiana è verde, bianca e rossa."},
  {it:"bianco / bianca",en:"white",type:"t-adj",cat:"Colors",note:"bianchi/bianche (hard c)",ex:"Vino bianco o rosso?"},
  {it:"nero / nera",en:"black",type:"t-adj",cat:"Colors",note:"4 forms: nero/nera/neri/nere",ex:"Caffè nero."},
  {it:"giallo / gialla",en:"yellow",type:"t-adj",cat:"Colors",note:"4 forms",ex:""},
  {it:"viola",en:"purple",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:"Una sciarpa viola."},
  {it:"rosa",en:"pink",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:""},
  {it:"grigio / grigia",en:"grey",type:"t-adj",cat:"Colors",note:"4 forms",ex:""},
  {it:"azzurro / azzurra",en:"light blue",type:"t-adj",cat:"Colors",note:"4 forms — Italy's sports color!",ex:"La maglia azzurra."},
  {it:"marrone",en:"brown",type:"t-adj",cat:"Colors",note:"-e type: marrone/marroni",ex:""},
  {it:"arancione",en:"orange",type:"t-adj",cat:"Colors",note:"-e type: arancione/arancioni",ex:""},

  // ── PREPOSITIONS ──────────────────────────────────────────────
  {it:"di",en:"of / from / about",type:"t-prep",cat:"Prepositions",note:"di + il = del, di + la = della, di + i = dei, di + gli = degli, di + le = delle",ex:"Un bicchiere di vino."},
  {it:"a",en:"to / at / in (cities)",type:"t-prep",cat:"Prepositions",note:"a + il = al, a + la = alla, a + i = ai",ex:"Vado a Roma. / Sono al bar."},
  {it:"da",en:"from / since / at (someone's place)",type:"t-prep",cat:"Prepositions",note:"da + il = dal, da + la = dalla",ex:"Vengo da Chicago. / Vado da Marco."},
  {it:"in",en:"in / to (countries, regions)",type:"t-prep",cat:"Prepositions",note:"in + il = nel, in + la = nella",ex:"Abito in Italia. / Vado in Francia."},
  {it:"con",en:"with",type:"t-prep",cat:"Prepositions",note:"con il = col (rare). Use 'con il' in speech.",ex:"Un cornetto con la crema."},
  {it:"su",en:"on / about",type:"t-prep",cat:"Prepositions",note:"su + il = sul, su + la = sulla",ex:"Il libro è sul tavolo."},
  {it:"per",en:"for / in order to",type:"t-prep",cat:"Prepositions",note:"NEVER contracts with articles",ex:"Per favore! / Un caffè per me."},
  {it:"tra / fra",en:"between / in (time)",type:"t-prep",cat:"Prepositions",note:"NEVER contracts — completely interchangeable",ex:"Arrivo tra dieci minuti."},
  {it:"al bar",en:"at the bar",type:"t-prep",cat:"Prepositions",note:"a + il → al",ex:"Faccio colazione al bar."},
  {it:"al ristorante",en:"at the restaurant",type:"t-prep",cat:"Prepositions",note:"a + il → al",ex:"Ci vediamo al ristorante."},
  {it:"del vino",en:"some wine",type:"t-prep",cat:"Prepositions",note:"di + il → del (partitive)",ex:"Vorrei del vino rosso."},
  {it:"in centro",en:"in the center",type:"t-prep",cat:"Prepositions",note:"in + area — no article needed",ex:"Abito in centro."},
  {it:"a casa",en:"at home / home",type:"t-prep",cat:"Prepositions",note:"a casa — no article!",ex:"Vado a casa."},

  // ── TRICKY PAIRS ──────────────────────────────────────────────
  {it:"sapere vs conoscere",en:"to know (fact/skill) vs to know (person/place)",type:"t-structure",cat:"Tricky Pairs",note:"sapere = Non lo so! / So cucinare. | conoscere = Conosco Marco. / Conosco Roma.",ex:"So che Roma è in Italia. / Conosco Roma bene."},
  {it:"essere vs stare",en:"to be (permanent) vs to be (temporary)",type:"t-structure",cat:"Tricky Pairs",note:"essere = identity, nationality | stare = health, mood, location right now",ex:"Sono italiano. / Come stai?"},
  {it:"guardare vs vedere",en:"to watch (active) vs to see (passive)",type:"t-structure",cat:"Tricky Pairs",note:"guardare = you choose to look | vedere = your eyes perceive / Ci vediamo! = See you!",ex:"Guardo la TV. / Ho visto Marco ieri."},
  {it:"ascoltare vs sentire",en:"to listen (active) vs to hear/feel (passive)",type:"t-structure",cat:"Tricky Pairs",note:"ascoltare = intentional | sentire = passive perception + to feel/smell",ex:"Ascolto la musica. / Sento freddo."},
  {it:"parlare vs dire",en:"to speak vs to say/tell",type:"t-structure",cat:"Tricky Pairs",note:"parlare = the act of speaking | dire = the content communicated",ex:"Parlo italiano. / Come si dice?"},
  {it:"portare vs prendere",en:"to bring (toward) vs to take (away/for yourself)",type:"t-structure",cat:"Tricky Pairs",note:"portare = bring TO someone | prendere = take for yourself / order",ex:"Mi porta il conto? / Prendo un caffè."},
  {it:"pensare vs credere",en:"to think (reflect) vs to think/believe (opinion)",type:"t-structure",cat:"Tricky Pairs",note:"pensare A = think about | credere = hold a belief / Credo di sì",ex:"Penso a te. / Credo di sì."},
  {it:"incontrare vs conoscere",en:"to meet (run into) vs to meet (first time)",type:"t-structure",cat:"Tricky Pairs",note:"incontrare = meeting someone you know | conoscere = first introduction",ex:"Ho incontrato Marco. / Piacere di conoscerti!"},

  // ── WORD PATTERNS ─────────────────────────────────────────────
  {it:"-tion → -zione",en:"nation = nazione, station = stazione",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine (la/una). Works 90% of the time!",ex:"La stazione / una conversazione / la lezione",words:[
       {it:"nazione",en:"nation"},
       {it:"stazione",en:"station"},
       {it:"lezione",en:"lesson"},
       {it:"conversazione",en:"conversation"},
       {it:"informazione",en:"information"},
       {it:"attenzione",en:"attention"},
       {it:"emozione",en:"emotion"},
       {it:"situazione",en:"situation"},
       {it:"relazione",en:"relationship"},
       {it:"posizione",en:"position"},
       {it:"tradizione",en:"tradition"},
       {it:"condizione",en:"condition"},
       {it:"opzione",en:"option"},
       {it:"intenzione",en:"intention"},
       {it:"direzione",en:"direction"},
       {it:"funzione",en:"function"},
       {it:"educazione",en:"education"},
       {it:"generazione",en:"generation"},
       {it:"organizzazione",en:"organization"},
       {it:"soluzione",en:"solution"}
      ]},
  {it:"-ly → -mente",en:"slowly = lentamente, normally = normalmente",type:"t-phrase",cat:"Word Patterns",note:"Add -mente to feminine adj. Drop -e if adj ends in -le/-re",ex:"lento → lenta → lentamente",words:[
       {it:"lentamente",en:"slowly"},
       {it:"velocemente",en:"quickly"},
       {it:"facilmente",en:"easily"},
       {it:"chiaramente",en:"clearly"},
       {it:"semplicemente",en:"simply"},
       {it:"naturalmente",en:"naturally"},
       {it:"normalmente",en:"normally"},
       {it:"fortunatamente",en:"fortunately"},
       {it:"sfortunatamente",en:"unfortunately"},
       {it:"probabilmente",en:"probably"},
       {it:"sicuramente",en:"surely / certainly"},
       {it:"esattamente",en:"exactly"},
       {it:"completamente",en:"completely"},
       {it:"totalmente",en:"totally"},
       {it:"finalmente",en:"finally"},
       {it:"veramente",en:"truly / really"},
       {it:"raramente",en:"rarely"},
       {it:"solamente",en:"only"},
       {it:"recentemente",en:"recently"},
       {it:"immediatamente",en:"immediately"}
      ]},
  {it:"-ty → -tà",en:"city = città, quality = qualità",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine. NEVER changes in plural! le città stays le città",ex:"la città / l'università / la qualità",words:[
       {it:"città",en:"city"},
       {it:"università",en:"university"},
       {it:"qualità",en:"quality"},
       {it:"velocità",en:"speed"},
       {it:"verità",en:"truth"},
       {it:"libertà",en:"liberty / freedom"},
       {it:"società",en:"society"},
       {it:"realtà",en:"reality"},
       {it:"possibilità",en:"possibility"},
       {it:"opportunità",en:"opportunity"},
       {it:"identità",en:"identity"},
       {it:"necessità",en:"necessity"},
       {it:"capacità",en:"capacity / ability"},
       {it:"felicità",en:"happiness"},
       {it:"difficoltà",en:"difficulty"},
       {it:"attività",en:"activity"},
       {it:"curiosità",en:"curiosity"},
       {it:"autorità",en:"authority"},
       {it:"priorità",en:"priority"},
       {it:"umanità",en:"humanity"}
      ]},
  {it:"-ence/-ance → -enza/-anza",en:"difference = differenza, patience = pazienza",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine. Related adj ends in -ente/-ante",ex:"paziente → pazienza / importante → importanza",words:[
       {it:"pazienza",en:"patience"},
       {it:"importanza",en:"importance"},
       {it:"esperienza",en:"experience"},
       {it:"differenza",en:"difference"},
       {it:"distanza",en:"distance"},
       {it:"presenza",en:"presence"},
       {it:"assenza",en:"absence"},
       {it:"influenza",en:"influence / flu"},
       {it:"frequenza",en:"frequency"},
       {it:"preferenza",en:"preference"},
       {it:"eleganza",en:"elegance"},
       {it:"tolleranza",en:"tolerance"},
       {it:"intelligenza",en:"intelligence"},
       {it:"indipendenza",en:"independence"},
       {it:"abbondanza",en:"abundance"},
       {it:"speranza",en:"hope"},
       {it:"violenza",en:"violence"},
       {it:"coscienza",en:"conscience"},
       {it:"conferenza",en:"conference"},
       {it:"urgenza",en:"urgency"}
      ]},
  {it:"-ist → -ista",en:"tourist = turista, artist = artista",type:"t-phrase",cat:"Word Patterns",note:"Same M/F singular. Plural: -isti (m) / -iste (f)",ex:"un turista / una turista / i turisti",words:[
       {it:"turista",en:"tourist"},
       {it:"artista",en:"artist"},
       {it:"dentista",en:"dentist"},
       {it:"pianista",en:"pianist"},
       {it:"tennista",en:"tennis player"},
       {it:"giornalista",en:"journalist"},
       {it:"farmacista",en:"pharmacist"},
       {it:"specialista",en:"specialist"},
       {it:"ottimista",en:"optimist"},
       {it:"pessimista",en:"pessimist"},
       {it:"autista",en:"driver"},
       {it:"barista",en:"barista / bartender"},
       {it:"musicista",en:"musician"},
       {it:"ciclista",en:"cyclist"},
       {it:"regista",en:"film director"},
       {it:"protagonista",en:"protagonist"},
       {it:"analista",en:"analyst"},
       {it:"realista",en:"realist"},
       {it:"artigiana / artigiano",en:"artisan"},
       {it:"violinista",en:"violinist"}
      ]},
  {it:"-al → -ale",en:"natural = naturale, national = nazionale",type:"t-phrase",cat:"Word Patterns",note:"-e type adj: 2 forms. Adverb: add -mente → naturalmente",ex:"naturale → naturalmente → natura",words:[
       {it:"naturale",en:"natural"},
       {it:"nazionale",en:"national"},
       {it:"speciale",en:"special"},
       {it:"normale",en:"normal"},
       {it:"finale",en:"final"},
       {it:"originale",en:"original"},
       {it:"internazionale",en:"international"},
       {it:"centrale",en:"central"},
       {it:"locale",en:"local"},
       {it:"generale",en:"general"},
       {it:"personale",en:"personal"},
       {it:"principale",en:"main / principal"},
       {it:"sociale",en:"social"},
       {it:"musicale",en:"musical"},
       {it:"culturale",en:"cultural"},
       {it:"digitale",en:"digital"},
       {it:"globale",en:"global"},
       {it:"ideale",en:"ideal"},
       {it:"essenziale",en:"essential"},
       {it:"legale",en:"legal"}
      ]},

  // ── FARE EXPRESSIONS ──────────────────────────────────────────
  {it:"fare colazione",en:"to have breakfast",type:"t-phrase",cat:"FARE Expressions",note:"Fixed phrase — cannot translate literally",ex:"Faccio colazione al bar ogni mattina."},
  {it:"fare una passeggiata",en:"to go for a walk",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Facciamo una passeggiata dopo cena?"},
  {it:"fare la doccia",en:"to take a shower",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio la doccia la mattina."},
  {it:"fare la spesa",en:"to go grocery shopping",type:"t-phrase",cat:"FARE Expressions",note:"la spesa = groceries",ex:"Vado a fare la spesa."},
  {it:"fare spese / shopping",en:"to go shopping (general)",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Il sabato faccio shopping."},
  {it:"fare un viaggio",en:"to take a trip",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Facciamo un viaggio in Sicilia!"},
  {it:"fare una domanda",en:"to ask a question",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Posso fare una domanda?"},
  {it:"fare i compiti",en:"to do homework",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio i compiti ogni sera."},
  {it:"fare sport",en:"to do sport / exercise",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio sport tre volte a settimana."},
  {it:"fare una foto",en:"to take a photo",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Posso fare una foto?"},
  {it:"fare freddo",en:"to be cold (weather)",type:"t-phrase",cat:"FARE Expressions",note:"weather = impersonal use of fare",ex:"Oggi fa molto freddo."},
  {it:"fare caldo",en:"to be hot (weather)",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"In estate fa caldissimo."},
  {it:"fare bel tempo",en:"to be nice weather",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Speriamo che faccia bel tempo!"},


  // ═══════════════════════════════════════════════════════════════
  // WAVE 1 ADDITIONS — parsed from Quick Reference Guides (2026-04-18)
  // ═══════════════════════════════════════════════════════════════

  // ── VERBS (22 new) ──
  {it:"viaggiare",en:"to travel",type:"t-are",cat:"Verbs",note:"io viaggio, tu viaggi, lui viaggia",ex:""},
  {it:"suonare",en:"to play (music/instrument)",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"annoiare",en:"to bore",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"riempire",en:"to fill",type:"t-ire",cat:"Verbs",note:"",ex:""},
  {it:"svuotare",en:"to empty",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"stancarsi",en:"to get tired (reflexive)",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"accontentare",en:"to satisfy / please",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"invecchiare",en:"to age / grow old",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"rinnovare",en:"to renew",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"allungare",en:"to lengthen",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"accorciare",en:"to shorten",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"riscaldare",en:"to heat up",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"raffreddare",en:"to cool down",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"facilitare",en:"to facilitate",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"complicare",en:"to complicate",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"rinforzare",en:"to reinforce / strengthen",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"rallentare",en:"to slow down",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"accelerare",en:"to speed up",type:"t-are",cat:"Verbs",note:"",ex:""},
  {it:"ingrandire",en:"to enlarge",type:"t-ireisc",cat:"Verbs",note:"",ex:""},
  {it:"rimpicciolire",en:"to shrink",type:"t-ireisc",cat:"Verbs",note:"",ex:""},
  {it:"abbellire",en:"to beautify",type:"t-ireisc",cat:"Verbs",note:"",ex:""},
  {it:"alzare",en:"to raise",type:"t-are",cat:"Verbs",note:"",ex:""},

  // ── PHRASES (205 new) ──
  {it:"c'era una volta",en:"once upon a time",type:"t-phrase",cat:"Phrases",note:"c'era = imperfect of c'è (there was)",ex:""},
  {it:"quanti ce ne sono?",en:"how many are there?",type:"t-phrase",cat:"Phrases",note:"ce ne sono = there are of them",ex:""},
  {it:"come si scrive?",en:"how do you write it? / how is it spelled?",type:"t-phrase",cat:"Phrases",note:"asking how to spell something",ex:""},
  {it:"come si fa?",en:"how do you do it?",type:"t-phrase",cat:"Phrases",note:"asking how something is done",ex:""},
  {it:"non si fa",en:"it's not done / you don't do that",type:"t-phrase",cat:"Phrases",note:"social rule expression",ex:""},
  {it:"si paga alla cassa",en:"you pay at the register",type:"t-phrase",cat:"Phrases",note:"common shop sign",ex:""},
  {it:"a che ora si apre?",en:"what time does it open?",type:"t-phrase",cat:"Phrases",note:"useful for shops/restaurants",ex:""},
  {it:"mi piace molto",en:"I really like it",type:"t-phrase",cat:"Phrases",note:"molto = a lot",ex:""},
  {it:"mi piace tantissimo",en:"I like it very much",type:"t-phrase",cat:"Phrases",note:"tantissimo = intensifier",ex:""},
  {it:"ti piace?",en:"do you like it? (informal)",type:"t-phrase",cat:"Phrases",note:"ti piace = does it please you?",ex:""},
  {it:"le piace?",en:"do you like it? (formal)",type:"t-phrase",cat:"Phrases",note:"formal/polite",ex:""},
  {it:"mi piacerebbe...",en:"I'd like... (I would like)",type:"t-phrase",cat:"Phrases",note:"conditional — more polite than voglio",ex:""},
  {it:"mi piace di più",en:"I prefer / I like it more",type:"t-phrase",cat:"Phrases",note:"alternative to preferire",ex:""},
  {it:"mi piace moltissimo",en:"I like it a lot / I love it",type:"t-phrase",cat:"Phrases",note:"intensifier",ex:""},
  {it:"lo adoro!",en:"I love it! / I adore it!",type:"t-phrase",cat:"Phrases",note:"adorare = to adore/love",ex:""},
  {it:"cosa ti piace?",en:"what do you like?",type:"t-phrase",cat:"Phrases",note:"asking preferences",ex:""},
  {it:"ho bisogno di aiuto",en:"I need help",type:"t-phrase",cat:"Phrases",note:"ho bisogno DI + noun",ex:""},
  {it:"ho paura",en:"I'm afraid",type:"t-phrase",cat:"Phrases",note:"ho paura = I have fear",ex:""},
  {it:"ho voglia di pizza",en:"I feel like pizza",type:"t-phrase",cat:"Phrases",note:"ho voglia di + noun",ex:""},
  {it:"ho voglia di uscire",en:"I feel like going out",type:"t-phrase",cat:"Phrases",note:"ho voglia di + infinitive",ex:""},
  {it:"non ho voglia",en:"I don't feel like it",type:"t-phrase",cat:"Phrases",note:"drop the di + noun if implied",ex:""},
  {it:"hai bisogno di qualcosa?",en:"do you need anything?",type:"t-phrase",cat:"Phrases",note:"hai = tu form of avere",ex:""},
  {it:"sta piovendo",en:"it's raining",type:"t-phrase",cat:"Phrases",note:"stare + gerund form of piovere",ex:""},
  {it:"sto arrivando!",en:"I'm coming! (on my way)",type:"t-phrase",cat:"Phrases",note:"very common expression",ex:""},
  {it:"sto pensando",en:"I'm thinking",type:"t-phrase",cat:"Phrases",note:"stare + gerund of pensare",ex:""},
  {it:"sto cercando",en:"I'm trying / I'm searching",type:"t-phrase",cat:"Phrases",note:"stare + gerund of cercare",ex:""},
  {it:"cosa stai facendo?",en:"what are you doing?",type:"t-phrase",cat:"Phrases",note:"stai = tu form of stare",ex:""},
  {it:"andiamo a mangiare!",en:"let's go eat!",type:"t-phrase",cat:"Phrases",note:"andiamo + a + infinitive",ex:""},
  {it:"andiamo!",en:"let's go!",type:"t-phrase",cat:"Phrases",note:"imperative/exhortative",ex:""},
  {it:"dove vai?",en:"where are you going?",type:"t-phrase",cat:"Phrases",note:"simple direction question",ex:""},
  {it:"posso entrare?",en:"can I come in?",type:"t-phrase",cat:"Phrases",note:"potere + infinitive — asking permission",ex:""},
  {it:"posso provare?",en:"can I try?",type:"t-phrase",cat:"Phrases",note:"potere + provare",ex:""},
  {it:"non posso venire",en:"I can't come",type:"t-phrase",cat:"Phrases",note:"non + potere + infinitive",ex:""},
  {it:"so cucinare",en:"I know how to cook",type:"t-phrase",cat:"Phrases",note:"sapere + infinitive = skill",ex:""},
  {it:"non so guidare",en:"I don't know how to drive",type:"t-phrase",cat:"Phrases",note:"sapere vs potere",ex:""},
  {it:"quanto costa?",en:"how much does it cost?",type:"t-phrase",cat:"Phrases",note:"quanto + singular verb",ex:""},
  {it:"quant'è?",en:"how much is it?",type:"t-phrase",cat:"Phrases",note:"quant'è = quanto è (apostrophe)",ex:""},
  {it:"quanti anni hai?",en:"how old are you?",type:"t-phrase",cat:"Phrases",note:"lit: how many years do you have?",ex:""},
  {it:"quanto tempo ci vuole?",en:"how long does it take?",type:"t-phrase",cat:"Phrases",note:"ci vuole = it takes",ex:""},
  {it:"un po'",en:"a little",type:"t-phrase",cat:"Phrases",note:"adverb of quantity",ex:""},
  {it:"basta!",en:"enough! / that's enough!",type:"t-phrase",cat:"Phrases",note:"exclamation",ex:""},
  {it:"neanche io",en:"me neither",type:"t-phrase",cat:"Phrases",note:"neanche/nemmeno = not even",ex:""},
  {it:"tutti e due",en:"both",type:"t-phrase",cat:"Phrases",note:"same as entrambi",ex:""},
  {it:"a volte",en:"sometimes",type:"t-phrase",cat:"Phrases",note:"= qualche volta",ex:""},
  {it:"una volta",en:"once",type:"t-phrase",cat:"Phrases",note:"Una volta abitavo a Milano.",ex:""},
  {it:"per la prima volta",en:"for the first time",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"per l'ultima volta",en:"for the last time",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"al latte",en:"with milk (flavoring)",type:"t-phrase",cat:"Phrases",note:"caffè al latte",ex:""},
  {it:"al limone",en:"with lemon (flavoring)",type:"t-phrase",cat:"Phrases",note:"tè al limone",ex:""},
  {it:"al pomodoro",en:"with tomato",type:"t-phrase",cat:"Phrases",note:"pizza al pomodoro / spaghetti al pomodoro",ex:""},
  {it:"con la crema",en:"with cream (filling)",type:"t-phrase",cat:"Phrases",note:"un cornetto con la crema",ex:""},
  {it:"con la marmellata",en:"with jam",type:"t-phrase",cat:"Phrases",note:"un cornetto con la marmellata",ex:""},
  {it:"senza ghiaccio",en:"without ice",type:"t-phrase",cat:"Phrases",note:"una coca senza ghiaccio",ex:""},
  {it:"un bicchiere di vino",en:"a glass of wine",type:"t-phrase",cat:"Phrases",note:"un bicchiere di vino rosso",ex:""},
  {it:"un quarto di vino",en:"a quarter liter of wine",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"mezza minerale",en:"half a liter of mineral water",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"per me...",en:"for me... (ordering)",type:"t-phrase",cat:"Phrases",note:"Per me, un caffè.",ex:""},
  {it:"per favore",en:"please (common)",type:"t-phrase",cat:"Phrases",note:"Il conto, per favore!",ex:""},
  {it:"per cortesia",en:"please (formal)",type:"t-phrase",cat:"Phrases",note:"Un caffè, per cortesia.",ex:""},
  {it:"sul menù",en:"on the menu",type:"t-phrase",cat:"Phrases",note:"Cosa c'è sul menù?",ex:""},
  {it:"del pane",en:"some bread",type:"t-phrase",cat:"Phrases",note:"Vorrei del pane.",ex:""},
  {it:"scusi!",en:"excuse me! (formal)",type:"t-phrase",cat:"Phrases",note:"used to get attention",ex:""},
  {it:"sì, dica!",en:"yes, go ahead! (waiter response)",type:"t-phrase",cat:"Phrases",note:"waiter's response to being called",ex:""},
  {it:"va bene così",en:"that's fine / this is good",type:"t-phrase",cat:"Phrases",note:"no more needed",ex:""},
  {it:"d'accordo",en:"alright / agreed / OK",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"un caffè corretto",en:"espresso with a splash of grappa",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"desidera?",en:"would you like? / can I help?",type:"t-phrase",cat:"Phrases",note:"formal waiter question",ex:""},
  {it:"i signori desiderano?",en:"what would the gentlemen/ladies like?",type:"t-phrase",cat:"Phrases",note:"formal restaurant greeting",ex:""},
  {it:"da mangiare?",en:"to eat?",type:"t-phrase",cat:"Phrases",note:"waiter asking about food order",ex:""},
  {it:"da bere?",en:"to drink?",type:"t-phrase",cat:"Phrases",note:"waiter asking about drink order",ex:""},
  {it:"subito",en:"right away / immediately",type:"t-phrase",cat:"Phrases",note:"D'accordo, subito!",ex:""},
  {it:"certo",en:"of course / certainly",type:"t-phrase",cat:"Phrases",note:"Certo, signora!",ex:""},
  {it:"anzi",en:"actually / rather",type:"t-phrase",cat:"Phrases",note:"No grazie... anzi, una birra.",ex:""},
  {it:"magari",en:"maybe / perhaps / I wish!",type:"t-phrase",cat:"Phrases",note:"Magari un caffè!",ex:""},
  {it:"l'aranciata",en:"orange soda / orangeade",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"l'aperitivo",en:"aperitif / pre-dinner drink",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il bicchiere di latte",en:"glass of milk",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"l'acqua minerale",en:"mineral water",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"lo spumante",en:"sparkling wine / prosecco",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la spremuta di pompelmo",en:"freshly squeezed grapefruit juice",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cappuccino",en:"cappuccino",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la birra",en:"beer",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cornetto",en:"croissant",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il caffè macchiato",en:"macchiato (coffee with a dash of milk)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il tè al limone",en:"lemon tea",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il tè al latte",en:"tea with milk",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"affettati misti",en:"mixed cold cuts",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"pomodori ripieni",en:"stuffed tomatoes",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"bruschette",en:"bruschetta (toasted bread)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"insalata di mare",en:"seafood salad",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"tortellini in brodo",en:"tortellini in broth",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"tagliatelle ai porcini",en:"tagliatelle with porcini mushrooms",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"lasagne al forno",en:"baked lasagna",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"risotto ai funghi",en:"mushroom risotto",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"minestrone",en:"minestrone soup",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"spaghetti ai frutti di mare",en:"spaghetti with seafood",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"spaghetti al pomodoro",en:"spaghetti with tomato sauce",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"cotoletta alla milanese",en:"Milanese breaded veal cutlet",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"braciola di maiale ai ferri",en:"grilled pork chop",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"pollo allo spiedo",en:"spit-roasted chicken",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"arrosto di vitello",en:"roast veal",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"trota alla mugnaia",en:"trout meunière",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"sogliola",en:"sole (fish)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"insalata mista",en:"mixed salad",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"patatine fritte",en:"french fries",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"purè di patate",en:"mashed potatoes",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"spinaci al burro",en:"spinach with butter",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"peperoni alla griglia",en:"grilled peppers",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"frutta fresca",en:"fresh fruit",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"macedonia",en:"fruit salad",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"gelato",en:"ice cream",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"panna cotta",en:"panna cotta",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il piatto",en:"the plate",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la forchetta",en:"the fork",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il coltello",en:"the knife",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cucchiaio",en:"the spoon",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cucchiaino",en:"the teaspoon",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il tovagliolo",en:"the napkin",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il bicchiere",en:"the glass",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il pane",en:"the bread",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"l'olio",en:"the oil",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"l'aceto",en:"the vinegar",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il sale",en:"the salt",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il pepe",en:"the pepper",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la bottiglia",en:"the bottle",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la carne",en:"the meat",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il pesce",en:"the fish",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il vino rosso",en:"red wine",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il vino bianco",en:"white wine",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"la pasta",en:"pasta",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il riso",en:"rice",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il caffè",en:"coffee",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il tè",en:"tea",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"antipasto / antipasti",en:"starter(s) / appetizer(s)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"primi piatti",en:"first courses (pasta/rice)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"secondi",en:"second courses (mains)",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"contorni",en:"side dishes",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il conto",en:"the check / bill",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cameriere",en:"the waiter",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"il cliente",en:"the customer",type:"t-phrase",cat:"Phrases",note:"food / restaurant noun",ex:""},
  {it:"terra",en:"earth / land",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"tempo",en:"time / weather",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"libro",en:"book",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"lavoro",en:"work / job",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"cucina",en:"cuisine / kitchen",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"viaggio",en:"trip / journey",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"forza",en:"strength / force",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"amico",en:"friend (m)",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"amica",en:"friend (f)",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"casa",en:"house / home",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"bevanda",en:"drink / beverage",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"raffreddore",en:"a cold (illness)",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"novità",en:"news / novelty",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"grandezza",en:"greatness / size",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"fatto",en:"fact / deed / done",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"detto",en:"saying / proverb / said",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"dato",en:"data / given",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"partita",en:"match / game",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"risposta",en:"answer / reply",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"piazza",en:"square / piazza",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"ragazzo",en:"boy / young man",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"ragazza",en:"girl / young woman",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"uomini",en:"men (pl.)",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"donne",en:"women (pl.)",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"centro",en:"center / downtown",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"periferia",en:"suburbs / outskirts",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"libreria",en:"bookshop",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"salotto",en:"living room",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Italia",en:"Italy",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Francia",en:"France",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"America",en:"America",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Giappone",en:"Japan",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Toscana",en:"Tuscany",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Lombardia",en:"Lombardy",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Sicilia",en:"Sicily",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Sardegna",en:"Sardinia",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"Corsica",en:"Corsica",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"mezzogiorno",en:"noon / midday",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"storia",en:"history / story",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"piano",en:"floor / piano",type:"t-phrase",cat:"Phrases",note:"noun (from word associations)",ex:""},
  {it:"parla lentamente, per favore",en:"speak slowly, please",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"puoi parlare lentamente?",en:"can you speak slowly? (informal)",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"può parlare lentamente?",en:"can you speak slowly? (formal)",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"dimmi la verità!",en:"tell me the truth!",type:"t-phrase",cat:"Phrases",note:"dire imperative: dimmi",ex:""},
  {it:"ascoltami!",en:"listen to me!",type:"t-phrase",cat:"Phrases",note:"imperative of ascoltare + mi",ex:""},
  {it:"portami...",en:"bring me...",type:"t-phrase",cat:"Phrases",note:"imperative of portare + mi",ex:"Portami il menu!"},
  {it:"guarda!",en:"look! / look out!",type:"t-phrase",cat:"Phrases",note:"imperative of guardare",ex:""},
  {it:"stai attento!",en:"be careful! (informal)",type:"t-phrase",cat:"Phrases",note:"stare + attento",ex:""},
  {it:"fammi vedere!",en:"let me see!",type:"t-phrase",cat:"Phrases",note:"fare + mi + vedere",ex:""},
  {it:"vediamo!",en:"let's see!",type:"t-phrase",cat:"Phrases",note:"vedere noi form",ex:""},
  {it:"non credo",en:"I don't think so / I don't believe it",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"mi credi?",en:"do you believe me?",type:"t-phrase",cat:"Phrases",note:"credere + indirect object",ex:""},
  {it:"cosa ne pensi?",en:"what do you think of it?",type:"t-phrase",cat:"Phrases",note:"pensare di = opinion",ex:""},
  {it:"ho chiesto dell'acqua",en:"I asked for water",type:"t-phrase",cat:"Phrases",note:"chiedere = request",ex:""},
  {it:"mi domando...",en:"I wonder...",type:"t-phrase",cat:"Phrases",note:"domandarsi = to wonder",ex:""},
  {it:"non ho capito",en:"I didn't understand",type:"t-phrase",cat:"Phrases",note:"past of capire",ex:""},
  {it:"un momento",en:"one moment",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"da asporto",en:"to take away / takeout",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"crepi!",en:"may it die! (response to in bocca al lupo)",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"buono studio!",en:"happy studying!",type:"t-phrase",cat:"Phrases",note:"common in Italian tutoring",ex:""},
  {it:"buon giorno",en:"good morning / good day",type:"t-phrase",cat:"Phrases",note:"before masc. noun: buon",ex:""},
  {it:"buona sera",en:"good evening",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"buona notte",en:"good night",type:"t-phrase",cat:"Phrases",note:"",ex:""},
  {it:"ciao",en:"hi / bye",type:"t-phrase",cat:"Phrases",note:"informal greeting",ex:""},
  {it:"grazie",en:"thank you",type:"t-phrase",cat:"Phrases",note:"",ex:""},

  // ── STRUCTURE (65 new) ──
  {it:"c'erano",en:"there were",type:"t-structure",cat:"Structure",note:"imperfect plural of c'è",ex:""},
  {it:"c'era",en:"there was",type:"t-structure",cat:"Structure",note:"imperfect singular of c'è",ex:""},
  {it:"eccolo! / eccola!",en:"there it is! / here it is!",type:"t-phrase",cat:"Structure",note:"ecco + lo/la (masc/fem pronoun)",ex:""},
  {it:"eccoci!",en:"here we are!",type:"t-phrase",cat:"Structure",note:"ecco + ci = we've arrived",ex:""},
  {it:"eccoli! / eccole!",en:"there they are!",type:"t-phrase",cat:"Structure",note:"eccoli (m) / eccole (f)",ex:""},
  {it:"ecco a Lei",en:"here you are (formal)",type:"t-phrase",cat:"Structure",note:"formal — handing something to someone",ex:""},
  {it:"ecco fatto!",en:"that's it! / done!",type:"t-phrase",cat:"Structure",note:"used alone",ex:""},
  {it:"ecco il punto",en:"here is the point",type:"t-phrase",cat:"Structure",note:"introducing the main point",ex:""},
  {it:"ecco perché",en:"here is why / that's why",type:"t-phrase",cat:"Structure",note:"explaining a reason",ex:""},
  {it:"si chiama...",en:"it's called... / one calls it...",type:"t-structure",cat:"Structure",note:"si + chiama = how something is called",ex:""},
  {it:"troppo / troppi / troppa / troppe",en:"too much / too many",type:"t-structure",cat:"Structure",note:"agrees with noun like adjective",ex:""},
  {it:"abbastanza",en:"enough",type:"t-structure",cat:"Structure",note:"adverb/adjective",ex:""},
  {it:"anche",en:"also / too",type:"t-structure",cat:"Structure",note:"positive — mid-sentence",ex:"Marco viene anche lui."},
  {it:"nemmeno",en:"not even",type:"t-structure",cat:"Structure",note:"interchangeable with neanche/neppure",ex:""},
  {it:"neppure",en:"not even",type:"t-structure",cat:"Structure",note:"interchangeable with neanche/nemmeno",ex:""},
  {it:"persino",en:"even",type:"t-structure",cat:"Structure",note:"Persino lui sa cucinare!",ex:""},
  {it:"non solo... ma anche...",en:"not only... but also...",type:"t-structure",cat:"Structure",note:"connector phrase",ex:""},
  {it:"entrambi",en:"both",type:"t-structure",cat:"Structure",note:"masc. plural; entrambe = fem.",ex:""},
  {it:"né... né...",en:"neither... nor...",type:"t-structure",cat:"Structure",note:"Non mangio né carne né pesce.",ex:""},
  {it:"o... o...",en:"either... or...",type:"t-structure",cat:"Structure",note:"O caffè o tè.",ex:""},
  {it:"quasi mai",en:"almost never",type:"t-structure",cat:"Structure",note:"non... quasi mai",ex:""},
  {it:"adesso",en:"now",type:"t-structure",cat:"Structure",note:"ADESSO = right now; ora is also 'now'",ex:""},
  {it:"ora",en:"now / hour",type:"t-structure",cat:"Structure",note:"ora = now; un'ora = an hour",ex:""},
  {it:"insieme",en:"together",type:"t-structure",cat:"Structure",note:"ENSEMBLE in English",ex:""},
  {it:"davvero",en:"really / truly",type:"t-structure",cat:"Structure",note:"DAVVERO? = really?",ex:""},
  {it:"purtroppo",en:"unfortunately",type:"t-structure",cat:"Structure",note:"opposite: fortunatamente",ex:""},
  {it:"fortunatamente",en:"fortunately",type:"t-structure",cat:"Structure",note:"opposite of purtroppo",ex:""},
  {it:"quasi",en:"almost",type:"t-structure",cat:"Structure",note:"quasi mai = almost never",ex:""},
  {it:"bene",en:"well (adverb)",type:"t-structure",cat:"Structure",note:"Eva parla bene l'italiano. (describes verb)",ex:""},
  {it:"male",en:"badly / poorly (adverb)",type:"t-structure",cat:"Structure",note:"opposite of bene",ex:""},
  {it:"lentamente",en:"slowly",type:"t-structure",cat:"Structure",note:"lento + -mente",ex:""},
  {it:"velocemente",en:"fast / quickly",type:"t-structure",cat:"Structure",note:"veloce + -mente",ex:""},
  {it:"facilmente",en:"easily",type:"t-structure",cat:"Structure",note:"facile + -mente",ex:""},
  {it:"difficilmente",en:"with difficulty",type:"t-structure",cat:"Structure",note:"difficile + -mente",ex:""},
  {it:"fortemente",en:"strongly",type:"t-structure",cat:"Structure",note:"forte + -mente",ex:""},
  {it:"attentamente",en:"carefully / attentively",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"probabilmente",en:"probably",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"immediatamente",en:"immediately",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"volentieri",en:"gladly",type:"t-structure",cat:"Structure",note:"from volere",ex:""},
  {it:"proprio",en:"really / truly / exactly",type:"t-structure",cat:"Structure",note:"intensifier",ex:""},
  {it:"veramente",en:"truly / really",type:"t-structure",cat:"Structure",note:"= davvero",ex:""},
  {it:"poi",en:"then / afterwards",type:"t-structure",cat:"Structure",note:"next in sequence",ex:""},
  {it:"invece",en:"instead / on the other hand",type:"t-structure",cat:"Structure",note:"contrast connector",ex:""},
  {it:"però",en:"however / but",type:"t-structure",cat:"Structure",note:"contrast",ex:""},
  {it:"percio",en:"therefore / so",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"dunque",en:"therefore / thus",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"ovunque",en:"everywhere",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"qui",en:"here",type:"t-structure",cat:"Structure",note:"vs là/lì",ex:""},
  {it:"qua",en:"here",type:"t-structure",cat:"Structure",note:"alternative to qui",ex:""},
  {it:"lì",en:"there",type:"t-structure",cat:"Structure",note:"vs qui",ex:""},
  {it:"là",en:"there",type:"t-structure",cat:"Structure",note:"far away / over there",ex:""},
  {it:"ogni",en:"every / each",type:"t-structure",cat:"Structure",note:"ogni giorno = every day",ex:""},
  {it:"tutti",en:"all / everyone",type:"t-structure",cat:"Structure",note:"masc. plural",ex:""},
  {it:"tutte",en:"all (f.pl.)",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"niente",en:"nothing",type:"t-structure",cat:"Structure",note:"Non mangio niente.",ex:""},
  {it:"qualcosa",en:"something",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"qualcuno",en:"someone",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"qualche",en:"some / a few",type:"t-structure",cat:"Structure",note:"qualche volta = sometimes",ex:""},
  {it:"con calma",en:"calmly",type:"t-structure",cat:"Structure",note:"manner expression",ex:""},
  {it:"con cura",en:"carefully / with care",type:"t-structure",cat:"Structure",note:"manner expression",ex:""},
  {it:"piuttosto",en:"rather",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"soltanto",en:"only / just",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"solo",en:"only / alone",type:"t-structure",cat:"Structure",note:"solo un momento = just a moment",ex:""},
  {it:"ancora una volta",en:"once again / one more time",type:"t-structure",cat:"Structure",note:"",ex:""},
  {it:"di nuovo",en:"again",type:"t-structure",cat:"Structure",note:"",ex:""},

  // ── ADJECTIVES (38 new) ──
  {it:"antico / antica",en:"ancient / old",type:"t-adj",cat:"Adjectives",note:"4 forms: antico/antica/antichi/antiche",ex:""},
  {it:"magro / magra",en:"thin / slim",type:"t-adj",cat:"Adjectives",note:"4 forms: magro/magra/magri/magre",ex:""},
  {it:"grasso / grassa",en:"fat",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"giovane",en:"young",type:"t-adj",cat:"Adjectives",note:"-e type: 2 forms (giovane/giovani)",ex:""},
  {it:"anziano / anziana",en:"elderly (more respectful than vecchio)",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"antipatico / antipatica",en:"unfriendly / unpleasant",type:"t-adj",cat:"Adjectives",note:"hard c: antipatici/antipatiche",ex:""},
  {it:"bravo / brava",en:"good (at something) / well-behaved",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"intelligente",en:"intelligent",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"divertente",en:"fun / amusing",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"gentile",en:"kind / polite",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"timido / timida",en:"shy / timid",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"coraggioso / coraggiosa",en:"brave / courageous",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"triste",en:"sad",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"lungo / lunga",en:"long",type:"t-adj",cat:"Adjectives",note:"hard g: lunghi/lunghe",ex:""},
  {it:"corto / corta",en:"short (length)",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"largo / larga",en:"wide",type:"t-adj",cat:"Adjectives",note:"hard g: larghi/larghe",ex:""},
  {it:"stretto / stretta",en:"narrow / tight / close",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"pulito / pulita",en:"clean",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"sporco / sporca",en:"dirty",type:"t-adj",cat:"Adjectives",note:"hard c: sporchi/sporche",ex:""},
  {it:"elegante",en:"elegant",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"comodo / comoda",en:"comfortable",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"scomodo / scomoda",en:"uncomfortable",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"costoso / costosa",en:"expensive",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"economico / economica",en:"economical / cheap",type:"t-adj",cat:"Adjectives",note:"hard c: economici/economiche",ex:""},
  {it:"silenzioso / silenziosa",en:"quiet / silent",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"rumoroso / rumorosa",en:"noisy",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"vicino / vicina",en:"near / close",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"lontano / lontana",en:"far / distant",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"sportivo / sportiva",en:"sporty / casual",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"stupido / stupida",en:"stupid",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"differente",en:"different",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"uguale",en:"equal / same",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"forte",en:"strong / loud",type:"t-adj",cat:"Adjectives",note:"-e type",ex:""},
  {it:"moderno / moderna",en:"modern",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"poco / poca",en:"little / few",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"molto / molta",en:"a lot / many / very",type:"t-adj",cat:"Adjectives",note:"4 forms",ex:""},
  {it:"pochi / poche",en:"few",type:"t-adj",cat:"Adjectives",note:"adjective form of 'poco'",ex:""},
  {it:"molti / molte",en:"many",type:"t-adj",cat:"Adjectives",note:"adjective form of 'molto'",ex:""},

  // ── COLORS (2 new) ──
  {it:"beige",en:"beige",type:"t-adj",cat:"Colors",note:"invariable color",ex:""},
  {it:"fucsia",en:"fuchsia / hot pink",type:"t-adj",cat:"Colors",note:"invariable color",ex:""},

  // ── PREPOSITIONS (38 new) ──
  {it:"senza",en:"without",type:"t-prep",cat:"Prepositions",note:"never contracts",ex:"senza ghiaccio = without ice"},
  {it:"tra",en:"between / among / in (time)",type:"t-prep",cat:"Prepositions",note:"interchangeable with fra; never contracts",ex:"tra 10 minuti"},
  {it:"fra",en:"between / among / in (time)",type:"t-prep",cat:"Prepositions",note:"interchangeable with tra; never contracts",ex:"fra una settimana"},
  {it:"del",en:"of the / some (m.s. before consonant)",type:"t-prep",cat:"Prepositions",note:"di + il",ex:"del pane = some bread"},
  {it:"dello",en:"of the (m.s. before s+cons or z)",type:"t-prep",cat:"Prepositions",note:"di + lo",ex:""},
  {it:"dell'",en:"of the (before vowel)",type:"t-prep",cat:"Prepositions",note:"di + l'",ex:""},
  {it:"della",en:"of the (f.s.)",type:"t-prep",cat:"Prepositions",note:"di + la",ex:""},
  {it:"dei",en:"of the / some (m.pl.)",type:"t-prep",cat:"Prepositions",note:"di + i",ex:""},
  {it:"degli",en:"of the (m.pl. before vowel or s+cons)",type:"t-prep",cat:"Prepositions",note:"di + gli",ex:""},
  {it:"delle",en:"of the / some (f.pl.)",type:"t-prep",cat:"Prepositions",note:"di + le",ex:""},
  {it:"al",en:"to/at the (m.s.)",type:"t-prep",cat:"Prepositions",note:"a + il",ex:"al bar, al ristorante"},
  {it:"allo",en:"to/at the (m.s. before s+cons/z)",type:"t-prep",cat:"Prepositions",note:"a + lo",ex:""},
  {it:"all'",en:"to/at the (before vowel)",type:"t-prep",cat:"Prepositions",note:"a + l'",ex:""},
  {it:"alla",en:"to/at the (f.s.)",type:"t-prep",cat:"Prepositions",note:"a + la",ex:"alla cassa"},
  {it:"ai",en:"to/at the (m.pl.)",type:"t-prep",cat:"Prepositions",note:"a + i",ex:""},
  {it:"agli",en:"to/at the (m.pl. before vowel/s+cons)",type:"t-prep",cat:"Prepositions",note:"a + gli",ex:""},
  {it:"alle",en:"to/at the (f.pl.) / at (time)",type:"t-prep",cat:"Prepositions",note:"a + le",ex:"alle 9 = at 9"},
  {it:"dal",en:"from the (m.s.)",type:"t-prep",cat:"Prepositions",note:"da + il",ex:""},
  {it:"dallo",en:"from the (m.s. before s+cons/z)",type:"t-prep",cat:"Prepositions",note:"da + lo",ex:""},
  {it:"dall'",en:"from the (before vowel)",type:"t-prep",cat:"Prepositions",note:"da + l'",ex:""},
  {it:"dalla",en:"from the (f.s.)",type:"t-prep",cat:"Prepositions",note:"da + la",ex:""},
  {it:"dai",en:"from the (m.pl.)",type:"t-prep",cat:"Prepositions",note:"da + i",ex:""},
  {it:"dagli",en:"from the (m.pl. before vowel/s+cons)",type:"t-prep",cat:"Prepositions",note:"da + gli",ex:""},
  {it:"dalle",en:"from the (f.pl.)",type:"t-prep",cat:"Prepositions",note:"da + le",ex:"dalle 9 alle 18"},
  {it:"nel",en:"in the (m.s.)",type:"t-prep",cat:"Prepositions",note:"in + il",ex:""},
  {it:"nello",en:"in the (m.s. before s+cons/z)",type:"t-prep",cat:"Prepositions",note:"in + lo",ex:""},
  {it:"nell'",en:"in the (before vowel)",type:"t-prep",cat:"Prepositions",note:"in + l'",ex:""},
  {it:"nella",en:"in the (f.s.)",type:"t-prep",cat:"Prepositions",note:"in + la",ex:""},
  {it:"nei",en:"in the (m.pl.)",type:"t-prep",cat:"Prepositions",note:"in + i",ex:""},
  {it:"negli",en:"in the (m.pl. before vowel/s+cons)",type:"t-prep",cat:"Prepositions",note:"in + gli",ex:""},
  {it:"nelle",en:"in the (f.pl.)",type:"t-prep",cat:"Prepositions",note:"in + le",ex:""},
  {it:"sul",en:"on the (m.s.)",type:"t-prep",cat:"Prepositions",note:"su + il",ex:"sul tavolo = on the table"},
  {it:"sullo",en:"on the (m.s. before s+cons/z)",type:"t-prep",cat:"Prepositions",note:"su + lo",ex:""},
  {it:"sull'",en:"on the (before vowel)",type:"t-prep",cat:"Prepositions",note:"su + l'",ex:""},
  {it:"sulla",en:"on the (f.s.)",type:"t-prep",cat:"Prepositions",note:"su + la",ex:"un film sulla storia"},
  {it:"sui",en:"on the (m.pl.)",type:"t-prep",cat:"Prepositions",note:"su + i",ex:""},
  {it:"sugli",en:"on the (m.pl. before vowel/s+cons)",type:"t-prep",cat:"Prepositions",note:"su + gli",ex:""},
  {it:"sulle",en:"on the (f.pl.)",type:"t-prep",cat:"Prepositions",note:"su + le",ex:""},

  // ── ARTICLES (9 new) ──
  {it:"il",en:"the (m.s. before consonant)",type:"t-prep",cat:"Articles",note:"definite article",ex:"il gelato"},
  {it:"lo",en:"the (m.s. before s+cons or z)",type:"t-prep",cat:"Articles",note:"definite article",ex:"lo spumante"},
  {it:"la",en:"the (f.s. before consonant)",type:"t-prep",cat:"Articles",note:"definite article",ex:"la pizza"},
  {it:"l'",en:"the (before vowel)",type:"t-prep",cat:"Articles",note:"definite article",ex:"l'antipasto, l'insalata"},
  {it:"i",en:"the (m.pl. before consonant)",type:"t-prep",cat:"Articles",note:"definite article",ex:"i gelati"},
  {it:"gli",en:"the (m.pl. before vowel or s+cons)",type:"t-prep",cat:"Articles",note:"definite article",ex:"gli antipasti"},
  {it:"le",en:"the (f.pl.)",type:"t-prep",cat:"Articles",note:"definite article",ex:"le pizze"},
  {it:"uno",en:"one (m.) / a",type:"t-prep",cat:"Articles",note:"number",ex:""},
  {it:"una",en:"one (f.) / a",type:"t-prep",cat:"Articles",note:"number",ex:""},

  // ── NUMBERS (10 new) ──
  {it:"due",en:"two",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"tre",en:"three",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"quattro",en:"four",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"cinque",en:"five",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"sei",en:"six",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"sette",en:"seven",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"otto",en:"eight",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"nove",en:"nine",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"dieci",en:"ten",type:"t-structure",cat:"Numbers",note:"number",ex:""},
  {it:"zero",en:"zero",type:"t-structure",cat:"Numbers",note:"number",ex:""},

  // ── NOUNS (75 new) ──
  {it:"fragole",en:"strawberries",type:"t-structure",cat:"Nouns",note:"food / restaurant noun",ex:""},
  {it:"tiramisù",en:"tiramisù",type:"t-structure",cat:"Nouns",note:"food / restaurant noun",ex:""},
  {it:"dessert",en:"dessert",type:"t-structure",cat:"Nouns",note:"food / restaurant noun",ex:""},
  {it:"anno",en:"year",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"voce",en:"voice",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"acqua",en:"water",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"pesce",en:"fish",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"luce",en:"light",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"notte",en:"night",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"sole",en:"sun",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"mare",en:"sea",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"porta",en:"door",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"mano",en:"hand",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"dente",en:"tooth",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"cuore",en:"heart",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"occhio",en:"eye",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"amore",en:"love",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"musica",en:"music",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"cibo",en:"food",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"studio",en:"study",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"bellezza",en:"beauty",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"velocità",en:"speed",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"pazienza",en:"patience",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"città",en:"city",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"scuola",en:"school",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"speranza",en:"hope",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"canzone",en:"song",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"cantante",en:"singer",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"partenza",en:"departure",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"sentimento",en:"feeling",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"calore",en:"heat",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"lunghezza",en:"length",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"lentezza",en:"slowness",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"stanchezza",en:"tiredness",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"noia",en:"boredom",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"pulizia",en:"cleanliness",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"altezza",en:"height",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"fine",en:"end",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"finalmente",en:"finally",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"scritto",en:"written",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"visto",en:"seen",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"autobus",en:"bus",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"treno",en:"train",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"macchina",en:"car",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"aereo",en:"plane",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"ombrello",en:"umbrella",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"regalo",en:"gift",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"medico",en:"doctor",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"moglie",en:"wife",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"fratello",en:"brother",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"prezzo",en:"price",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"verità",en:"truth",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"lingua",en:"language",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"radio",en:"radio",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"albergo",en:"hotel",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"uomo",en:"man",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"donna",en:"woman",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"dio",en:"God",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"pioggia",en:"rain",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"università",en:"university",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"ufficio",en:"office",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"banca",en:"bank",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"bagno",en:"bathroom",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"estate",en:"summer",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"inverno",en:"winter",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"mattina",en:"morning",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"sera",en:"evening",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"stagione",en:"season",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"minuto",en:"minute",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"settimana",en:"week",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"mezzanotte",en:"midnight",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"cena",en:"dinner",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"festa",en:"party",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"colazione",en:"breakfast",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},
  {it:"schermo",en:"screen",type:"t-structure",cat:"Nouns",note:"noun (from word associations)",ex:""},

  // ── TRICKY PAIRS (2 new) ──
  {it:"chiedere vs domandare",en:"to ask for vs to ask (a question)",type:"t-phrase",cat:"Tricky Pairs",note:"chiedere = request something / more common; domandare = more formal question",ex:""},
  {it:"domandarsi",en:"to wonder / ask oneself",type:"t-phrase",cat:"Tricky Pairs",note:"",ex:"Mi domando perché."},

  // ── FARE EXPRESSIONS (8 new) ──
  {it:"fare un giro",en:"to go for a stroll / ride",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Facciamo un giro in città stasera?"},
  {it:"fare il bagno",en:"to take a bath",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Il bambino fa il bagno la sera."},
  {it:"fare la fila / la coda",en:"to queue / stand in line",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"C'è molta fila — dobbiamo aspettare."},
  {it:"fare il biglietto",en:"to buy a ticket",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Dove posso fare il biglietto?"},
  {it:"fare la valigia",en:"to pack a suitcase",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Ho già fatto la valigia per domani."},
  {it:"fare il bucato",en:"to do laundry",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Faccio il bucato il lunedì."},
  {it:"fare una gita",en:"to go on a day trip",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Facciamo una gita a Firenze sabato."},
  {it:"fare brutto tempo",en:"to be bad weather",type:"t-phrase",cat:"FARE Expressions",note:"FARE + fixed noun expression",ex:"Fa brutto tempo oggi."},

];
