// Italian vocabulary — add new entries here as you get worksheets from your tutor.
// Each entry: { it, en, type, cat, note, ex }
// Types: t-are, t-ere, t-ire, t-ireisc, t-irr, t-phrase, t-adj, t-prep, t-structure, t-think
// Cats: Verbs, Phrases, Structure, Adjectives, Colors, Prepositions, Tricky Pairs, Word Patterns, FARE Expressions

const VOCAB = [

  // ── VERBS -ARE ──────────────────────────────────────────────
  {it:"abitare",en:"to live (somewhere)",type:"t-are",cat:"Verbs",note:"abito, abiti, abita, abitiamo, abitate, abitano",ex:"Abito a Chicago."},
  {it:"amare",en:"to love",type:"t-are",cat:"Verbs",note:"amo, ami, ama, amiamo, amate, amano",ex:"Amo l'italiano!"},
  {it:"ascoltare",en:"to listen to",type:"t-are",cat:"Verbs",note:"ascolto, ascolti, ascolta, ascoltiamo, ascoltate, ascoltano",ex:"Ascolto la musica."},
  {it:"aspettare",en:"to wait for",type:"t-are",cat:"Verbs",note:"aspetto, aspetti, aspetta...",ex:"Aspetta un momento!"},
  {it:"ballare",en:"to dance",type:"t-are",cat:"Verbs",note:"ballo, balli, balla, balliamo, ballate, ballano",ex:"Vuoi ballare?"},
  {it:"camminare",en:"to walk",type:"t-are",cat:"Verbs",note:"cammino, cammini, cammina...",ex:"Ho camminato tutto il giorno."},
  {it:"cantare",en:"to sing",type:"t-are",cat:"Verbs",note:"canto, canti, canta, cantiamo, cantate, cantano",ex:"Lui canta bene."},
  {it:"cenare",en:"to have dinner",type:"t-are",cat:"Verbs",note:"ceno, ceni, cena, ceniamo, cenate, cenano",ex:"A che ora ceni?"},
  {it:"cercare",en:"to look for / try",type:"t-are",cat:"Verbs",note:"cerco, cerchi, cerca...",ex:"Sto cercando il ristorante."},
  {it:"chiamare",en:"to call",type:"t-are",cat:"Verbs",note:"chiamo, chiami, chiama...",ex:"Ti chiamo dopo."},
  {it:"comprare",en:"to buy",type:"t-are",cat:"Verbs",note:"compro, compri, compra...",ex:"Voglio comprare un caffè."},
  {it:"cucinare",en:"to cook",type:"t-are",cat:"Verbs",note:"cucino, cucini, cucina...",ex:"Cucino la pasta stasera."},
  {it:"domandare",en:"to ask (a question)",type:"t-are",cat:"Verbs",note:"domando, domandi, domanda...",ex:"Mi ha domandato una cosa."},
  {it:"guardare",en:"to watch / look at",type:"t-are",cat:"Verbs",note:"guardo, guardi, guarda...",ex:"Guardo la TV la sera."},
  {it:"imparare",en:"to learn",type:"t-are",cat:"Verbs",note:"imparo, impari, impara...",ex:"Sto imparando l'italiano."},
  {it:"incontrare",en:"to meet / run into",type:"t-are",cat:"Verbs",note:"incontro, incontri, incontra...",ex:"Ho incontrato Marco al bar."},
  {it:"lavorare",en:"to work",type:"t-are",cat:"Verbs",note:"lavoro, lavori, lavora...",ex:"Lavoro in centro."},
  {it:"mangiare",en:"to eat",type:"t-are",cat:"Verbs",note:"mangio, mangi, mangia...",ex:"Cosa mangi a pranzo?"},
  {it:"pagare",en:"to pay",type:"t-are",cat:"Verbs",note:"pago, paghi, paga...",ex:"Posso pagare con la carta?"},
  {it:"parlare",en:"to speak",type:"t-are",cat:"Verbs",note:"parlo, parli, parla...",ex:"Parli italiano?"},
  {it:"pensare",en:"to think / consider",type:"t-are",cat:"Verbs",note:"penso, pensi, pensa...",ex:"Cosa pensi?"},
  {it:"portare",en:"to carry / bring",type:"t-are",cat:"Verbs",note:"porto, porti, porta...",ex:"Mi porta il conto?"},
  {it:"sperare",en:"to hope",type:"t-are",cat:"Verbs",note:"spero, speri, spera...",ex:"Speriamo!"},
  {it:"studiare",en:"to study",type:"t-are",cat:"Verbs",note:"studio, studi, studia...",ex:"Studio l'italiano ogni giorno."},
  {it:"tornare",en:"to return / come back",type:"t-are",cat:"Verbs",note:"torno, torni, torna...",ex:"Torno a casa alle 7."},
  {it:"trovare",en:"to find",type:"t-are",cat:"Verbs",note:"trovo, trovi, trova...",ex:"Non riesco a trovare il ristorante."},
  {it:"dimenticare",en:"to forget",type:"t-are",cat:"Verbs",note:"dimentico, dimentichi, dimentica...",ex:"Ho dimenticato!"},
  {it:"ricordare",en:"to remember",type:"t-are",cat:"Verbs",note:"ricordo / mi ricordo...",ex:"Non ricordo il suo nome."},
  {it:"sembrare",en:"to seem / look like",type:"t-are",cat:"Verbs",note:"sembro, sembri, sembra...",ex:"Sembra buono!"},

  // ── VERBS -ERE ──────────────────────────────────────────────
  {it:"chiedere",en:"to ask for / request",type:"t-ere",cat:"Verbs",note:"chiedo, chiedi, chiede...",ex:"Posso chiederti una cosa?"},
  {it:"conoscere",en:"to know (person/place)",type:"t-ere",cat:"Verbs",note:"conosco, conosci, conosce...",ex:"Conosci Marco?"},
  {it:"credere",en:"to think / believe",type:"t-ere",cat:"Verbs",note:"credo, credi, crede...",ex:"Credo di sì."},
  {it:"leggere",en:"to read",type:"t-ere",cat:"Verbs",note:"leggo, leggi, legge...",ex:"Leggo ogni sera."},
  {it:"prendere",en:"to take / order",type:"t-ere",cat:"Verbs",note:"prendo, prendi, prende...",ex:"Prendo un caffè."},
  {it:"scrivere",en:"to write",type:"t-ere",cat:"Verbs",note:"scrivo, scrivi, scrive...",ex:"Scrivo un messaggio."},
  {it:"vedere",en:"to see",type:"t-ere",cat:"Verbs",note:"vedo, vedi, vede...",ex:"Ci vediamo domani!"},
  {it:"vivere",en:"to live (be alive)",type:"t-ere",cat:"Verbs",note:"vivo, vivi, vive...",ex:"Vivo a Chicago."},
  {it:"decidere",en:"to decide",type:"t-ere",cat:"Verbs",note:"decido, decidi, decide...",ex:"Ho deciso!"},

  // ── VERBS -IRE ──────────────────────────────────────────────
  {it:"aprire",en:"to open",type:"t-ire",cat:"Verbs",note:"apro, apri, apre...",ex:"A che ora si apre?"},
  {it:"dormire",en:"to sleep",type:"t-ire",cat:"Verbs",note:"dormo, dormi, dorme...",ex:"Dormo tardi il weekend."},
  {it:"partire",en:"to leave / depart",type:"t-ire",cat:"Verbs",note:"parto, parti, parte...",ex:"Parto per Roma domani."},
  {it:"scoprire",en:"to discover",type:"t-ire",cat:"Verbs",note:"scopro, scopri, scopre...",ex:"Scopro sempre cose nuove."},
  {it:"sentire",en:"to hear / feel",type:"t-ire",cat:"Verbs",note:"sento, senti, sente...",ex:"Non ti sento bene."},

  // ── VERBS -IRE/ISC ────────────────────────────────────────────
  {it:"capire",en:"to understand",type:"t-ireisc",cat:"Verbs",note:"capisco, capisci, capisce, capiamo, capite, capiscono",ex:"Non capisco. Puoi ripetere?"},
  {it:"finire",en:"to finish",type:"t-ireisc",cat:"Verbs",note:"finisco, finisci, finisce, finiamo, finite, finiscono",ex:"A che ora finisce?"},
  {it:"preferire",en:"to prefer",type:"t-ireisc",cat:"Verbs",note:"preferisco, preferisci, preferisce...",ex:"Preferisco il vino rosso."},
  {it:"pulire",en:"to clean",type:"t-ireisc",cat:"Verbs",note:"pulisco, pulisci, pulisce...",ex:"Pulisco la casa il sabato."},

  // ── IRREGULAR VERBS ───────────────────────────────────────────
  {it:"andare",en:"to go",type:"t-irr",cat:"Verbs",note:"vado, vai, va, andiamo, andate, vanno",ex:"Vado al bar."},
  {it:"avere",en:"to have",type:"t-irr",cat:"Verbs",note:"ho, hai, ha, abbiamo, avete, hanno",ex:"Ho fame!"},
  {it:"bere",en:"to drink",type:"t-irr",cat:"Verbs",note:"bevo, bevi, beve, beviamo, bevete, bevono",ex:"Cosa bevi?"},
  {it:"dare",en:"to give",type:"t-irr",cat:"Verbs",note:"do, dai, dà, diamo, date, danno",ex:"Mi dà il conto?"},
  {it:"dire",en:"to say / tell",type:"t-irr",cat:"Verbs",note:"dico, dici, dice, diciamo, dite, dicono",ex:"Come si dice?"},
  {it:"essere",en:"to be",type:"t-irr",cat:"Verbs",note:"sono, sei, è, siamo, siete, sono",ex:"Sono americano."},
  {it:"fare",en:"to do / make",type:"t-irr",cat:"Verbs",note:"faccio, fai, fa, facciamo, fate, fanno",ex:"Cosa fai stasera?"},
  {it:"piacere",en:"to please (mi piace = I like)",type:"t-irr",cat:"Verbs",note:"piaccio, piaci, piace, piacciamo, piacete, piacciono",ex:"Mi piace l'italiano!"},
  {it:"potere",en:"to be able / can",type:"t-irr",cat:"Verbs",note:"posso, puoi, può, possiamo, potete, possono",ex:"Posso avere il conto?"},
  {it:"rimanere",en:"to stay / remain",type:"t-irr",cat:"Verbs",note:"rimango, rimani, rimane...",ex:"Rimango a casa stasera."},
  {it:"sapere",en:"to know (fact/skill)",type:"t-irr",cat:"Verbs",note:"so, sai, sa, sappiamo, sapete, sanno",ex:"Non lo so!"},
  {it:"stare",en:"to be / stay (temp.)",type:"t-irr",cat:"Verbs",note:"sto, stai, sta, stiamo, state, stanno",ex:"Come stai?"},
  {it:"uscire",en:"to go out",type:"t-irr",cat:"Verbs",note:"esco, esci, esce, usciamo, uscite, escono",ex:"Esci stasera?"},
  {it:"venire",en:"to come",type:"t-irr",cat:"Verbs",note:"vengo, vieni, viene, veniamo, venite, vengono",ex:"Vieni con me?"},
  {it:"volere",en:"to want",type:"t-irr",cat:"Verbs",note:"voglio, vuoi, vuole, vogliamo, volete, vogliono",ex:"Vorrei un caffè, per favore."},
  {it:"dovere",en:"to have to / must",type:"t-irr",cat:"Verbs",note:"devo, devi, deve, dobbiamo, dovete, devono",ex:"Devo studiare."},
  {it:"sentirsi",en:"to feel (about yourself)",type:"t-irr",cat:"Verbs",note:"mi sento, ti senti, si sente...",ex:"Come ti senti?"},

  // ── KEY PHRASES ───────────────────────────────────────────────
  {it:"Credo di sì.",en:"I think so.",type:"t-phrase",cat:"Phrases",note:"Use when answering yes/no with uncertainty",ex:"Viene Marco? Credo di sì."},
  {it:"Credo di no.",en:"I don't think so.",type:"t-phrase",cat:"Phrases",note:"Uncertain negative answer",ex:"È chiuso? Credo di no."},
  {it:"Non ci credo!",en:"I don't believe it! No way!",type:"t-phrase",cat:"Phrases",note:"Expressing disbelief or surprise",ex:""},
  {it:"Non lo so.",en:"I don't know.",type:"t-phrase",cat:"Phrases",note:"Most used phrase — say it with confidence!",ex:"Dove sei? Non lo so!"},
  {it:"Speriamo!",en:"Let's hope! Hopefully!",type:"t-phrase",cat:"Phrases",note:"One of the most common Italian expressions",ex:"Fa bel tempo? Speriamo!"},
  {it:"Non capisco.",en:"I don't understand.",type:"t-phrase",cat:"Phrases",note:"Say this confidently — Italians will help you",ex:"Puoi ripetere?"},
  {it:"Ho capito!",en:"Got it! I understand!",type:"t-phrase",cat:"Phrases",note:"Confirming comprehension",ex:""},
  {it:"Ho dimenticato!",en:"I forgot!",type:"t-phrase",cat:"Phrases",note:"Very useful for a beginner",ex:"Il portafoglio! Ho dimenticato!"},
  {it:"Ho deciso!",en:"I've decided!",type:"t-phrase",cat:"Phrases",note:"Final answer!",ex:"Prendo gli spaghetti. Ho deciso!"},
  {it:"Sembra buono!",en:"It looks/seems good!",type:"t-phrase",cat:"Phrases",note:"Reacting to food, a plan, an idea",ex:""},
  {it:"Mi sento bene.",en:"I feel fine / well.",type:"t-phrase",cat:"Phrases",note:"Standard answer to 'Come stai?'",ex:""},
  {it:"Ci vediamo!",en:"See you! / Talk soon!",type:"t-phrase",cat:"Phrases",note:"Common goodbye",ex:""},
  {it:"Come stai?",en:"How are you?",type:"t-phrase",cat:"Phrases",note:"Informal — use with friends",ex:""},
  {it:"Sto bene, grazie.",en:"I'm fine, thank you.",type:"t-phrase",cat:"Phrases",note:"Answer to come stai?",ex:""},
  {it:"Prego!",en:"You're welcome! / Please!",type:"t-phrase",cat:"Phrases",note:"Response to grazie",ex:""},
  {it:"Scusa! / Scusi!",en:"Excuse me! / Sorry!",type:"t-phrase",cat:"Phrases",note:"Scusa = informal, Scusi = formal",ex:""},
  {it:"Vorrei...",en:"I would like...",type:"t-phrase",cat:"Phrases",note:"Most polite way to order — always use this!",ex:"Vorrei un caffè, per favore."},
  {it:"Posso avere...?",en:"Can I have...?",type:"t-phrase",cat:"Phrases",note:"Polite request",ex:"Posso avere il conto?"},
  {it:"Il conto, per favore!",en:"The check, please!",type:"t-phrase",cat:"Phrases",note:"Essential restaurant phrase",ex:""},
  {it:"Dov'è il bagno?",en:"Where is the bathroom?",type:"t-phrase",cat:"Phrases",note:"Most universal travel phrase",ex:""},
  {it:"Parla lentamente, per favore.",en:"Please speak slowly.",type:"t-phrase",cat:"Phrases",note:"Essential for learners!",ex:""},
  {it:"Non parlo bene l'italiano.",en:"I don't speak Italian well.",type:"t-phrase",cat:"Phrases",note:"Humble opener — Italians love it",ex:""},
  {it:"Sto imparando l'italiano.",en:"I'm learning Italian.",type:"t-phrase",cat:"Phrases",note:"Great conversation starter",ex:""},
  {it:"Correggimi, per favore!",en:"Correct me, please!",type:"t-phrase",cat:"Phrases",note:"Ask natives to help you improve",ex:""},
  {it:"Che coincidenza!",en:"What a coincidence!",type:"t-phrase",cat:"Phrases",note:"You'll hear this constantly",ex:""},
  {it:"In bocca al lupo!",en:"Good luck! (lit: into the wolf's mouth)",type:"t-phrase",cat:"Phrases",note:"Response: Crepi! (May it die!)",ex:""},
  {it:"Da portare via.",en:"To go / Takeaway.",type:"t-phrase",cat:"Phrases",note:"At a bar or restaurant",ex:""},
  {it:"Posso pagare con la carta?",en:"Can I pay by card?",type:"t-phrase",cat:"Phrases",note:"Very important in Italy!",ex:""},
  {it:"Si accettano carte?",en:"Do you accept cards?",type:"t-phrase",cat:"Phrases",note:"accettare = to accept",ex:""},
  {it:"Anch'io!",en:"Me too!",type:"t-phrase",cat:"Phrases",note:"anch' + io — apostrophe before vowel",ex:""},
  {it:"Neanche io.",en:"Me neither.",type:"t-phrase",cat:"Phrases",note:"negative version of anch'io",ex:""},
  {it:"Non c'è problema!",en:"No problem!",type:"t-phrase",cat:"Phrases",note:"One of the most useful phrases",ex:""},
  {it:"Che cosa?",en:"What? / What thing?",type:"t-phrase",cat:"Phrases",note:"cosa = thing — che cosa = what",ex:""},
  {it:"Qualcosa non va.",en:"Something is wrong.",type:"t-phrase",cat:"Phrases",note:"qualcosa = something",ex:""},
  {it:"Niente, grazie.",en:"Nothing, thanks.",type:"t-phrase",cat:"Phrases",note:"niente = nothing",ex:""},

  // ── STRUCTURE WORDS ───────────────────────────────────────────
  {it:"C'è...",en:"There is...",type:"t-structure",cat:"Structure",note:"c'è = ci + è — singular",ex:"C'è un bar qui vicino?"},
  {it:"Ci sono...",en:"There are...",type:"t-structure",cat:"Structure",note:"ci sono = plural",ex:"Ci sono tavoli liberi?"},
  {it:"Non c'è...",en:"There isn't...",type:"t-structure",cat:"Structure",note:"Non c'è problema = No problem!",ex:"Non c'è problema!"},
  {it:"Ecco!",en:"Here it is! / There you go!",type:"t-structure",cat:"Structure",note:"For presenting or pointing out something",ex:"Ecco il menù!"},
  {it:"Eccomi!",en:"Here I am!",type:"t-structure",cat:"Structure",note:"ecco + mi",ex:"Eccomi! Sono arrivato!"},
  {it:"Come si dice?",en:"How do you say...?",type:"t-structure",cat:"Structure",note:"si + verb = impersonal construction",ex:"Come si dice 'hello' in italiano?"},
  {it:"Si mangia bene qui.",en:"The food is good here.",type:"t-structure",cat:"Structure",note:"si = impersonal — one eats well here",ex:""},
  {it:"Mi piace...",en:"I like... (singular thing)",type:"t-structure",cat:"Structure",note:"The THING is the subject — it pleases me",ex:"Mi piace la pasta."},
  {it:"Mi piacciono...",en:"I like... (plural things)",type:"t-structure",cat:"Structure",note:"plural thing = mi piacciono",ex:"Mi piacciono i cani."},
  {it:"Ho bisogno di...",en:"I need...",type:"t-structure",cat:"Structure",note:"Always DI after bisogno!",ex:"Ho bisogno di aiuto."},
  {it:"Ho voglia di...",en:"I feel like...",type:"t-structure",cat:"Structure",note:"ho voglia di = I fancy something",ex:"Ho voglia di pizza!"},
  {it:"Sto + -ando/-endo",en:"I am doing... (right now)",type:"t-structure",cat:"Structure",note:"-ARE → -ando | -ERE/-IRE → -endo",ex:"Sto mangiando."},
  {it:"Vado a + infinitive",en:"I'm going to...",type:"t-structure",cat:"Structure",note:"Always A between vado and next verb",ex:"Vado a mangiare."},
  {it:"Andiamo a...!",en:"Let's go...!",type:"t-structure",cat:"Structure",note:"andiamo = let's go",ex:"Andiamo a mangiare!"},
  {it:"Ho fame.",en:"I'm hungry.",type:"t-structure",cat:"Structure",note:"avere + noun for physical states",ex:"Ho fame — andiamo a mangiare!"},
  {it:"Ho sete.",en:"I'm thirsty.",type:"t-structure",cat:"Structure",note:"ho sete = I have thirst",ex:""},
  {it:"Ho caldo.",en:"I'm hot.",type:"t-structure",cat:"Structure",note:"ho caldo = I have heat",ex:""},
  {it:"Ho freddo.",en:"I'm cold.",type:"t-structure",cat:"Structure",note:"ho freddo = I have cold",ex:""},
  {it:"Ho sonno.",en:"I'm sleepy.",type:"t-structure",cat:"Structure",note:"ho sonno = I have sleep",ex:""},
  {it:"Ho ragione.",en:"I'm right.",type:"t-structure",cat:"Structure",note:"ho ragione = I have reason",ex:""},
  {it:"Ho torto.",en:"I'm wrong.",type:"t-structure",cat:"Structure",note:"ho torto = I have wrong",ex:""},
  {it:"Già",en:"already",type:"t-structure",cat:"Structure",note:"Ho già mangiato. = I already ate.",ex:""},
  {it:"Non ancora",en:"not yet",type:"t-structure",cat:"Structure",note:"Non ho ancora mangiato. = I haven't eaten yet.",ex:""},
  {it:"Non più",en:"no longer / not anymore",type:"t-structure",cat:"Structure",note:"Non abito più a Roma.",ex:""},
  {it:"Ancora",en:"still / again / yet",type:"t-structure",cat:"Structure",note:"Abito ancora qui. = I still live here.",ex:""},
  {it:"Sempre",en:"always",type:"t-structure",cat:"Structure",note:"goes AFTER the verb",ex:"Vado sempre al bar."},
  {it:"Spesso",en:"often",type:"t-structure",cat:"Structure",note:"goes AFTER the verb",ex:"Mangio spesso la pizza."},
  {it:"Di solito",en:"usually",type:"t-structure",cat:"Structure",note:"goes at START of sentence",ex:"Di solito studio la sera."},
  {it:"Qualche volta",en:"sometimes",type:"t-structure",cat:"Structure",note:"goes at START of sentence",ex:"Qualche volta cucino a casa."},
  {it:"Non... mai",en:"never",type:"t-structure",cat:"Structure",note:"non BEFORE verb, mai AFTER",ex:"Non mangio mai carne."},
  {it:"Forse",en:"maybe / perhaps",type:"t-structure",cat:"Structure",note:"Forse sì, forse no.",ex:"Viene? Forse."},
  {it:"Quindi",en:"therefore / so",type:"t-structure",cat:"Structure",note:"logical consequence",ex:"Studio, quindi imparo."},
  {it:"Allora",en:"so / well then",type:"t-structure",cat:"Structure",note:"starting a sentence — very common!",ex:"Allora, andiamo?"},
  {it:"Finora",en:"so far / until now",type:"t-structure",cat:"Structure",note:"fino + ora",ex:"Finora amo questa città."},
  {it:"Davvero?",en:"Really? / Truly?",type:"t-structure",cat:"Structure",note:"davvero = really/truly",ex:""},
  {it:"Subito!",en:"Right away! / Immediately!",type:"t-structure",cat:"Structure",note:"Very common in service situations",ex:""},

  // ── ADJECTIVES ────────────────────────────────────────────────
  {it:"alto / alta",en:"tall",type:"t-adj",cat:"Adjectives",note:"-o/-a type: alti/alte (plural)",ex:"È molto alto."},
  {it:"basso / bassa",en:"short (height)",type:"t-adj",cat:"Adjectives",note:"-o/-a type: bassi/basse",ex:""},
  {it:"bello / bella",en:"beautiful / nice",type:"t-adj",cat:"Adjectives",note:"bel before m. nouns: bel ragazzo",ex:"Che bella città!"},
  {it:"brutto / brutta",en:"ugly / bad",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Fa brutto tempo oggi."},
  {it:"buono / buona",en:"good (quality)",type:"t-adj",cat:"Adjectives",note:"buon before masc. noun: buon giorno",ex:"È molto buono!"},
  {it:"cattivo / cattiva",en:"bad / mean",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:""},
  {it:"grande",en:"big / large",type:"t-adj",cat:"Adjectives",note:"-e type: 2 forms only (grande/grandi)",ex:"Una grande opportunità."},
  {it:"piccolo / piccola",en:"small / little",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Un piccolo problema."},
  {it:"caldo / calda",en:"hot / warm",type:"t-adj",cat:"Adjectives",note:"Ho caldo = I'm hot",ex:"È molto caldo oggi!"},
  {it:"freddo / fredda",en:"cold",type:"t-adj",cat:"Adjectives",note:"Ho freddo = I'm cold",ex:"Fa freddo!"},
  {it:"simpatico / simpatica",en:"friendly / likeable",type:"t-adj",cat:"Adjectives",note:"simpatici/simpatiche (hard c)",ex:"È molto simpatico."},
  {it:"stanco / stanca",en:"tired",type:"t-adj",cat:"Adjectives",note:"stanchi/stanche (hard c)",ex:"Sono stanco — ho camminato tutto il giorno."},
  {it:"contento / contenta",en:"happy / pleased",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Sono molto contento!"},
  {it:"facile",en:"easy",type:"t-adj",cat:"Adjectives",note:"-e type: facile/facili",ex:"È più facile di così."},
  {it:"difficile",en:"difficult",type:"t-adj",cat:"Adjectives",note:"-e type",ex:"È molto difficile."},
  {it:"veloce",en:"fast",type:"t-adj",cat:"Adjectives",note:"-e type | velocità = speed",ex:"Mangia troppo veloce!"},
  {it:"lento / lenta",en:"slow",type:"t-adj",cat:"Adjectives",note:"lentamente = slowly",ex:"Parla lentamente, per favore."},
  {it:"nuovo / nuova",en:"new",type:"t-adj",cat:"Adjectives",note:"-o/-a type | novità = news",ex:"Ho una nuova amica."},
  {it:"vecchio / vecchia",en:"old",type:"t-adj",cat:"Adjectives",note:"vecchi/vecchie (hard c)",ex:"Una vecchia tradizione."},
  {it:"aperto / aperta",en:"open",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"Il bar è aperto."},
  {it:"chiuso / chiusa",en:"closed",type:"t-adj",cat:"Adjectives",note:"-o/-a type",ex:"È chiuso il lunedì."},
  {it:"interessante",en:"interesting",type:"t-adj",cat:"Adjectives",note:"-e type",ex:"È molto interessante!"},
  {it:"noioso / noiosa",en:"boring",type:"t-adj",cat:"Adjectives",note:"-o/-a type | noia = boredom",ex:""},
  {it:"pieno / piena",en:"full",type:"t-adj",cat:"Adjectives",note:"-o/-a type | riempire = to fill",ex:"Sono pieno! Ho mangiato troppo."},
  {it:"vuoto / vuota",en:"empty",type:"t-adj",cat:"Adjectives",note:"-o/-a type | void",ex:"Il bicchiere è vuoto."},

  // ── COLORS ────────────────────────────────────────────────────
  {it:"rosso / rossa",en:"red",type:"t-adj",cat:"Colors",note:"4 forms: rosso/rossa/rossi/rosse",ex:"Vino rosso, per favore."},
  {it:"blu",en:"dark blue",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:"Una giacca blu."},
  {it:"verde",en:"green",type:"t-adj",cat:"Colors",note:"-e type: verde/verdi",ex:"La bandiera italiana è verde, bianca e rossa."},
  {it:"bianco / bianca",en:"white",type:"t-adj",cat:"Colors",note:"bianchi/bianche (hard c)",ex:"Vino bianco o rosso?"},
  {it:"nero / nera",en:"black",type:"t-adj",cat:"Colors",note:"4 forms: nero/nera/neri/nere",ex:"Caffè nero."},
  {it:"giallo / gialla",en:"yellow",type:"t-adj",cat:"Colors",note:"4 forms",ex:""},
  {it:"viola",en:"purple",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:"Una sciarpa viola."},
  {it:"rosa",en:"pink",type:"t-adj",cat:"Colors",note:"NEVER changes — invariable!",ex:""},
  {it:"grigio / grigia",en:"grey",type:"t-adj",cat:"Colors",note:"4 forms",ex:""},
  {it:"azzurro / azzurra",en:"light blue",type:"t-adj",cat:"Colors",note:"4 forms — Italy's sports color!",ex:"La maglia azzurra."},
  {it:"marrone",en:"brown",type:"t-adj",cat:"Colors",note:"-e type: marrone/marroni",ex:""},
  {it:"arancione",en:"orange",type:"t-adj",cat:"Colors",note:"-e type: arancione/arancioni",ex:""},

  // ── PREPOSITIONS ──────────────────────────────────────────────
  {it:"di",en:"of / from / about",type:"t-prep",cat:"Prepositions",note:"di + il = del, di + la = della, di + i = dei, di + gli = degli, di + le = delle",ex:"Un bicchiere di vino."},
  {it:"a",en:"to / at / in (cities)",type:"t-prep",cat:"Prepositions",note:"a + il = al, a + la = alla, a + i = ai",ex:"Vado a Roma. / Sono al bar."},
  {it:"da",en:"from / since / at (someone's place)",type:"t-prep",cat:"Prepositions",note:"da + il = dal, da + la = dalla",ex:"Vengo da Chicago. / Vado da Marco."},
  {it:"in",en:"in / to (countries, regions)",type:"t-prep",cat:"Prepositions",note:"in + il = nel, in + la = nella",ex:"Abito in Italia. / Vado in Francia."},
  {it:"con",en:"with",type:"t-prep",cat:"Prepositions",note:"con il = col (rare). Use 'con il' in speech.",ex:"Un cornetto con la crema."},
  {it:"su",en:"on / about",type:"t-prep",cat:"Prepositions",note:"su + il = sul, su + la = sulla",ex:"Il libro è sul tavolo."},
  {it:"per",en:"for / in order to",type:"t-prep",cat:"Prepositions",note:"NEVER contracts with articles",ex:"Per favore! / Un caffè per me."},
  {it:"tra / fra",en:"between / in (time)",type:"t-prep",cat:"Prepositions",note:"NEVER contracts — completely interchangeable",ex:"Arrivo tra dieci minuti."},
  {it:"al bar",en:"at the bar",type:"t-prep",cat:"Prepositions",note:"a + il → al",ex:"Faccio colazione al bar."},
  {it:"al ristorante",en:"at the restaurant",type:"t-prep",cat:"Prepositions",note:"a + il → al",ex:"Ci vediamo al ristorante."},
  {it:"del vino",en:"some wine",type:"t-prep",cat:"Prepositions",note:"di + il → del (partitive)",ex:"Vorrei del vino rosso."},
  {it:"in centro",en:"in the center",type:"t-prep",cat:"Prepositions",note:"in + area — no article needed",ex:"Abito in centro."},
  {it:"a casa",en:"at home / home",type:"t-prep",cat:"Prepositions",note:"a casa — no article!",ex:"Vado a casa."},

  // ── TRICKY PAIRS ──────────────────────────────────────────────
  {it:"sapere vs conoscere",en:"to know (fact/skill) vs to know (person/place)",type:"t-structure",cat:"Tricky Pairs",note:"sapere = Non lo so! / So cucinare. | conoscere = Conosco Marco. / Conosco Roma.",ex:"So che Roma è in Italia. / Conosco Roma bene."},
  {it:"essere vs stare",en:"to be (permanent) vs to be (temporary)",type:"t-structure",cat:"Tricky Pairs",note:"essere = identity, nationality | stare = health, mood, location right now",ex:"Sono italiano. / Come stai?"},
  {it:"guardare vs vedere",en:"to watch (active) vs to see (passive)",type:"t-structure",cat:"Tricky Pairs",note:"guardare = you choose to look | vedere = your eyes perceive / Ci vediamo! = See you!",ex:"Guardo la TV. / Ho visto Marco ieri."},
  {it:"ascoltare vs sentire",en:"to listen (active) vs to hear/feel (passive)",type:"t-structure",cat:"Tricky Pairs",note:"ascoltare = intentional | sentire = passive perception + to feel/smell",ex:"Ascolto la musica. / Sento freddo."},
  {it:"parlare vs dire",en:"to speak vs to say/tell",type:"t-structure",cat:"Tricky Pairs",note:"parlare = the act of speaking | dire = the content communicated",ex:"Parlo italiano. / Come si dice?"},
  {it:"portare vs prendere",en:"to bring (toward) vs to take (away/for yourself)",type:"t-structure",cat:"Tricky Pairs",note:"portare = bring TO someone | prendere = take for yourself / order",ex:"Mi porta il conto? / Prendo un caffè."},
  {it:"pensare vs credere",en:"to think (reflect) vs to think/believe (opinion)",type:"t-structure",cat:"Tricky Pairs",note:"pensare A = think about | credere = hold a belief / Credo di sì",ex:"Penso a te. / Credo di sì."},
  {it:"incontrare vs conoscere",en:"to meet (run into) vs to meet (first time)",type:"t-structure",cat:"Tricky Pairs",note:"incontrare = meeting someone you know | conoscere = first introduction",ex:"Ho incontrato Marco. / Piacere di conoscerti!"},

  // ── WORD PATTERNS ─────────────────────────────────────────────
  {it:"-tion → -zione",en:"nation = nazione, station = stazione",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine (la/una). Works 90% of the time!",ex:"La stazione / una conversazione / la lezione"},
  {it:"-ly → -mente",en:"slowly = lentamente, normally = normalmente",type:"t-phrase",cat:"Word Patterns",note:"Add -mente to feminine adj. Drop -e if adj ends in -le/-re",ex:"lento → lenta → lentamente"},
  {it:"-ty → -tà",en:"city = città, quality = qualità",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine. NEVER changes in plural! le città stays le città",ex:"la città / l'università / la qualità"},
  {it:"-ence/-ance → -enza/-anza",en:"difference = differenza, patience = pazienza",type:"t-phrase",cat:"Word Patterns",note:"ALL feminine. Related adj ends in -ente/-ante",ex:"paziente → pazienza / importante → importanza"},
  {it:"-ist → -ista",en:"tourist = turista, artist = artista",type:"t-phrase",cat:"Word Patterns",note:"Same M/F singular. Plural: -isti (m) / -iste (f)",ex:"un turista / una turista / i turisti"},
  {it:"-al → -ale",en:"natural = naturale, national = nazionale",type:"t-phrase",cat:"Word Patterns",note:"-e type adj: 2 forms. Adverb: add -mente → naturalmente",ex:"naturale → naturalmente → natura"},

  // ── FARE EXPRESSIONS ──────────────────────────────────────────
  {it:"fare colazione",en:"to have breakfast",type:"t-phrase",cat:"FARE Expressions",note:"Fixed phrase — cannot translate literally",ex:"Faccio colazione al bar ogni mattina."},
  {it:"fare una passeggiata",en:"to go for a walk",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Facciamo una passeggiata dopo cena?"},
  {it:"fare la doccia",en:"to take a shower",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio la doccia la mattina."},
  {it:"fare la spesa",en:"to go grocery shopping",type:"t-phrase",cat:"FARE Expressions",note:"la spesa = groceries",ex:"Vado a fare la spesa."},
  {it:"fare spese / shopping",en:"to go shopping (general)",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Il sabato faccio shopping."},
  {it:"fare un viaggio",en:"to take a trip",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Facciamo un viaggio in Sicilia!"},
  {it:"fare una domanda",en:"to ask a question",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Posso fare una domanda?"},
  {it:"fare i compiti",en:"to do homework",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio i compiti ogni sera."},
  {it:"fare sport",en:"to do sport / exercise",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Faccio sport tre volte a settimana."},
  {it:"fare una foto",en:"to take a photo",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Posso fare una foto?"},
  {it:"fare freddo",en:"to be cold (weather)",type:"t-phrase",cat:"FARE Expressions",note:"weather = impersonal use of fare",ex:"Oggi fa molto freddo."},
  {it:"fare caldo",en:"to be hot (weather)",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"In estate fa caldissimo."},
  {it:"fare bel tempo",en:"to be nice weather",type:"t-phrase",cat:"FARE Expressions",note:"",ex:"Speriamo che faccia bel tempo!"},
];
