name = "italiano-sync"
main = "src/index.js"
compatibility_date = "2024-09-01"

# Replace id below with the ID printed by `wrangler kv namespace create KNOWN`
[[kv_namespaces]]
binding = "KNOWN"
id = "ebc2a1979ed04d1eb106b2fa785b1967"
